

#if (NUCODEGEN_LLSI0)
void LLSI0_Init()
{
    /* This function make LLSI0 module be ready to transfer */
    LLSI_Open(LLSI0, NUCODEGEN_LLSI0_LLSI_MODE, NUCODEGEN_LLSI0_OUTPUT_FORMAT, NUCODEGEN_LLSI0_BUSCLOCK, NUCODEGEN_LLSI0_TRANSFER_TIME,
              NUCODEGEN_LLSI0_T0H_TIME, NUCODEGEN_LLSI0_T1H_TIME, NUCODEGEN_LLSI0_RESET_TIME, NUCODEGEN_LLSI0_PIXEL_COUNT, NUCODEGEN_LLSI0_IDLE_OUTPUT_STATE);

#if (NUCODEGEN_LLSI0_LLSI_MODE==LLSI_MODE_SW)

    /* Set FIFO threshold */
    LLSI_SetFIFO(LLSI0, NUCODEGEN_LLSI0_TX_THRESHOLD);

#endif /* NUCODEGEN_LLSI0_LLSI_MODE==LLSI_MODE_SW */

#if (NUCODEGEN_LLSI0_INT_EN)

    /* Enable interrupt type */
    LLSI_EnableInt(LLSI0, NUCODEGEN_LLSI0_INT_SEL);

    /* Enable interrupt function */
    NVIC_EnableIRQ(LLSI0_IRQn);

#endif /* NUCODEGEN_LLSI0_INT_EN */

#if (NUCODEGEN_LLSI0_RESET_COMMAND_EN)

    /* Enable reset command function */
    LLSI_ENABLE_RESET_COMMAND(LLSI0);

#endif /* NUCODEGEN_LLSI0_RESET_COMMAND_EN */
}
#endif /* NUCODEGEN_LLSI0 */

#if (NUCODEGEN_LLSI1)
void LLSI1_Init()
{
    /* This function make LLSI1 module be ready to transfer */
    LLSI_Open(LLSI1, NUCODEGEN_LLSI1_LLSI_MODE, NUCODEGEN_LLSI1_OUTPUT_FORMAT, NUCODEGEN_LLSI1_BUSCLOCK, NUCODEGEN_LLSI1_TRANSFER_TIME,
              NUCODEGEN_LLSI1_T0H_TIME, NUCODEGEN_LLSI1_T1H_TIME, NUCODEGEN_LLSI1_RESET_TIME, NUCODEGEN_LLSI1_PIXEL_COUNT, NUCODEGEN_LLSI1_IDLE_OUTPUT_STATE);

#if (NUCODEGEN_LLSI1_LLSI_MODE==LLSI_MODE_SW)

    /* Set FIFO threshold */
    LLSI_SetFIFO(LLSI1, NUCODEGEN_LLSI1_TX_THRESHOLD);

#endif /* NUCODEGEN_LLSI1_LLSI_MODE==LLSI_MODE_SW */

#if (NUCODEGEN_LLSI1_INT_EN)

    /* Enable interrupt type */
    LLSI_EnableInt(LLSI1, NUCODEGEN_LLSI1_INT_SEL);

    /* Enable interrupt function */
    NVIC_EnableIRQ(LLSI1_IRQn);

#endif /* NUCODEGEN_LLSI1_INT_EN */

#if (NUCODEGEN_LLSI1_RESET_COMMAND_EN)

    /* Enable reset command function */
    LLSI_ENABLE_RESET_COMMAND(LLSI1);

#endif /* NUCODEGEN_LLSI1_RESET_COMMAND_EN */
}
#endif /* NUCODEGEN_LLSI1 */

#if (NUCODEGEN_LLSI2)
void LLSI2_Init()
{
    /* This function make LLSI2 module be ready to transfer */
    LLSI_Open(LLSI2, NUCODEGEN_LLSI2_LLSI_MODE, NUCODEGEN_LLSI2_OUTPUT_FORMAT, NUCODEGEN_LLSI2_BUSCLOCK, NUCODEGEN_LLSI2_TRANSFER_TIME,
              NUCODEGEN_LLSI2_T0H_TIME, NUCODEGEN_LLSI2_T1H_TIME, NUCODEGEN_LLSI2_RESET_TIME, NUCODEGEN_LLSI2_PIXEL_COUNT, NUCODEGEN_LLSI2_IDLE_OUTPUT_STATE);

#if (NUCODEGEN_LLSI2_LLSI_MODE==LLSI_MODE_SW)

    /* Set FIFO threshold */
    LLSI_SetFIFO(LLSI2, NUCODEGEN_LLSI2_TX_THRESHOLD);

#endif /* NUCODEGEN_LLSI2_LLSI_MODE==LLSI_MODE_SW */

#if (NUCODEGEN_LLSI2_INT_EN)

    /* Enable interrupt type */
    LLSI_EnableInt(LLSI2, NUCODEGEN_LLSI2_INT_SEL);

    /* Enable interrupt function */
    NVIC_EnableIRQ(LLSI2_IRQn);

#endif /* NUCODEGEN_LLSI2_INT_EN */

#if (NUCODEGEN_LLSI2_RESET_COMMAND_EN)

    /* Enable reset command function */
    LLSI_ENABLE_RESET_COMMAND(LLSI2);

#endif /* NUCODEGEN_LLSI2_RESET_COMMAND_EN */
}
#endif /* NUCODEGEN_LLSI2 */

#if (NUCODEGEN_LLSI3)
void LLSI3_Init()
{
    /* This function make LLSI3 module be ready to transfer */
    LLSI_Open(LLSI3, NUCODEGEN_LLSI3_LLSI_MODE, NUCODEGEN_LLSI3_OUTPUT_FORMAT, NUCODEGEN_LLSI3_BUSCLOCK, NUCODEGEN_LLSI3_TRANSFER_TIME,
              NUCODEGEN_LLSI3_T0H_TIME, NUCODEGEN_LLSI3_T1H_TIME, NUCODEGEN_LLSI3_RESET_TIME, NUCODEGEN_LLSI3_PIXEL_COUNT, NUCODEGEN_LLSI3_IDLE_OUTPUT_STATE);

#if (NUCODEGEN_LLSI3_LLSI_MODE==LLSI_MODE_SW)

    /* Set FIFO threshold */
    LLSI_SetFIFO(LLSI3, NUCODEGEN_LLSI3_TX_THRESHOLD);

#endif /* NUCODEGEN_LLSI3_LLSI_MODE==LLSI_MODE_SW */

#if (NUCODEGEN_LLSI3_INT_EN)

    /* Enable interrupt type */
    LLSI_EnableInt(LLSI3, NUCODEGEN_LLSI3_INT_SEL);

    /* Enable interrupt function */
    NVIC_EnableIRQ(LLSI3_IRQn);

#endif /* NUCODEGEN_LLSI3_INT_EN */

#if (NUCODEGEN_LLSI3_RESET_COMMAND_EN)

    /* Enable reset command function */
    LLSI_ENABLE_RESET_COMMAND(LLSI3);

#endif /* NUCODEGEN_LLSI3_RESET_COMMAND_EN */
}
#endif /* NUCODEGEN_LLSI3*/


#if (NUCODEGEN_LLSI4)
void LLSI4_Init()
{
    /* This function make LLSI4 module be ready to transfer */
    LLSI_Open(LLSI4, NUCODEGEN_LLSI4_LLSI_MODE, NUCODEGEN_LLSI4_OUTPUT_FORMAT, NUCODEGEN_LLSI4_BUSCLOCK, NUCODEGEN_LLSI4_TRANSFER_TIME,
              NUCODEGEN_LLSI4_T0H_TIME, NUCODEGEN_LLSI4_T1H_TIME, NUCODEGEN_LLSI4_RESET_TIME, NUCODEGEN_LLSI4_PIXEL_COUNT, NUCODEGEN_LLSI4_IDLE_OUTPUT_STATE);

#if (NUCODEGEN_LLSI4_LLSI_MODE==LLSI_MODE_SW)

    /* Set FIFO threshold */
    LLSI_SetFIFO(LLSI4, NUCODEGEN_LLSI4_TX_THRESHOLD);

#endif /* NUCODEGEN_LLSI4_LLSI_MODE==LLSI_MODE_SW */

#if (NUCODEGEN_LLSI4_INT_EN)

    /* Enable interrupt type */
    LLSI_EnableInt(LLSI4, NUCODEGEN_LLSI4_INT_SEL);

    /* Enable interrupt function */
    NVIC_EnableIRQ(LLSI4_IRQn);

#endif /* NUCODEGEN_LLSI4_INT_EN */

#if (NUCODEGEN_LLSI4_RESET_COMMAND_EN)

    /* Enable reset command function */
    LLSI_ENABLE_RESET_COMMAND(LLSI4);

#endif /* NUCODEGEN_LLSI4_RESET_COMMAND_EN */
}
#endif /* NUCODEGEN_LLSI4 */

#if (NUCODEGEN_LLSI5)
void LLSI5_Init()
{
    /* This function make LLSI5 module be ready to transfer */
    LLSI_Open(LLSI5, NUCODEGEN_LLSI5_LLSI_MODE, NUCODEGEN_LLSI5_OUTPUT_FORMAT, NUCODEGEN_LLSI5_BUSCLOCK, NUCODEGEN_LLSI5_TRANSFER_TIME,
              NUCODEGEN_LLSI5_T0H_TIME, NUCODEGEN_LLSI5_T1H_TIME, NUCODEGEN_LLSI5_RESET_TIME, NUCODEGEN_LLSI5_PIXEL_COUNT, NUCODEGEN_LLSI5_IDLE_OUTPUT_STATE);

#if (NUCODEGEN_LLSI5_LLSI_MODE==LLSI_MODE_SW)

    /* Set FIFO threshold */
    LLSI_SetFIFO(LLSI5, NUCODEGEN_LLSI5_TX_THRESHOLD);

#endif /* NUCODEGEN_LLSI5_LLSI_MODE==LLSI_MODE_SW */

#if (NUCODEGEN_LLSI5_INT_EN)

    /* Enable interrupt type */
    LLSI_EnableInt(LLSI5, NUCODEGEN_LLSI5_INT_SEL);

    /* Enable interrupt function */
    NVIC_EnableIRQ(LLSI5_IRQn);

#endif /* NUCODEGEN_LLSI5_INT_EN */

#if (NUCODEGEN_LLSI5_RESET_COMMAND_EN)

    /* Enable reset command function */
    LLSI_ENABLE_RESET_COMMAND(LLSI5);

#endif /* NUCODEGEN_LLSI5_RESET_COMMAND_EN */
}
#endif /* NUCODEGEN_LLSI5 */

#if (NUCODEGEN_LLSI6)
void LLSI6_Init()
{
    /* This function make LLSI6 module be ready to transfer */
    LLSI_Open(LLSI6, NUCODEGEN_LLSI6_LLSI_MODE, NUCODEGEN_LLSI6_OUTPUT_FORMAT, NUCODEGEN_LLSI6_BUSCLOCK, NUCODEGEN_LLSI6_TRANSFER_TIME,
              NUCODEGEN_LLSI6_T0H_TIME, NUCODEGEN_LLSI6_T1H_TIME, NUCODEGEN_LLSI6_RESET_TIME, NUCODEGEN_LLSI6_PIXEL_COUNT, NUCODEGEN_LLSI6_IDLE_OUTPUT_STATE);

#if (NUCODEGEN_LLSI6_LLSI_MODE==LLSI_MODE_SW)

    /* Set FIFO threshold */
    LLSI_SetFIFO(LLSI6, NUCODEGEN_LLSI6_TX_THRESHOLD);

#endif /* NUCODEGEN_LLSI6_LLSI_MODE==LLSI_MODE_SW */

#if (NUCODEGEN_LLSI6_INT_EN)

    /* Enable interrupt type */
    LLSI_EnableInt(LLSI6, NUCODEGEN_LLSI6_INT_SEL);

    /* Enable interrupt function */
    NVIC_EnableIRQ(LLSI6_IRQn);

#endif /* NUCODEGEN_LLSI6_INT_EN */

#if (NUCODEGEN_LLSI6_RESET_COMMAND_EN)

    /* Enable reset command function */
    LLSI_ENABLE_RESET_COMMAND(LLSI6);

#endif /* NUCODEGEN_LLSI6_RESET_COMMAND_EN */
}
#endif /* NUCODEGEN_LLSI6*/

#if (NUCODEGEN_LLSI7)
void LLSI7_Init()
{
    /* This function make LLSI7 module be ready to transfer */
    LLSI_Open(LLSI7, NUCODEGEN_LLSI7_LLSI_MODE, NUCODEGEN_LLSI7_OUTPUT_FORMAT, NUCODEGEN_LLSI7_BUSCLOCK, NUCODEGEN_LLSI7_TRANSFER_TIME,
              NUCODEGEN_LLSI7_T0H_TIME, NUCODEGEN_LLSI7_T1H_TIME, NUCODEGEN_LLSI7_RESET_TIME, NUCODEGEN_LLSI7_PIXEL_COUNT, NUCODEGEN_LLSI7_IDLE_OUTPUT_STATE);

#if (NUCODEGEN_LLSI7_LLSI_MODE==LLSI_MODE_SW)

    /* Set FIFO threshold */
    LLSI_SetFIFO(LLSI7, NUCODEGEN_LLSI7_TX_THRESHOLD);

#endif /* NUCODEGEN_LLSI7_LLSI_MODE==LLSI_MODE_SW */

#if (NUCODEGEN_LLSI7_INT_EN)

    /* Enable interrupt type */
    LLSI_EnableInt(LLSI7, NUCODEGEN_LLSI7_INT_SEL);

    /* Enable interrupt function */
    NVIC_EnableIRQ(LLSI7_IRQn);

#endif /* NUCODEGEN_LLSI7_INT_EN */

#if (NUCODEGEN_LLSI7_RESET_COMMAND_EN)

    /* Enable reset command function */
    LLSI_ENABLE_RESET_COMMAND(LLSI7);

#endif /* NUCODEGEN_LLSI7_RESET_COMMAND_EN */
}
#endif /* NUCODEGEN_LLSI7 */

#if (NUCODEGEN_LLSI8)
void LLSI8_Init()
{
    /* This function make LLSI8 module be ready to transfer */
    LLSI_Open(LLSI8, NUCODEGEN_LLSI8_LLSI_MODE, NUCODEGEN_LLSI8_OUTPUT_FORMAT, NUCODEGEN_LLSI8_BUSCLOCK, NUCODEGEN_LLSI8_TRANSFER_TIME,
              NUCODEGEN_LLSI8_T0H_TIME, NUCODEGEN_LLSI8_T1H_TIME, NUCODEGEN_LLSI8_RESET_TIME, NUCODEGEN_LLSI8_PIXEL_COUNT, NUCODEGEN_LLSI8_IDLE_OUTPUT_STATE);

#if (NUCODEGEN_LLSI8_LLSI_MODE==LLSI_MODE_SW)

    /* Set FIFO threshold */
    LLSI_SetFIFO(LLSI8, NUCODEGEN_LLSI8_TX_THRESHOLD);

#endif /* NUCODEGEN_LLSI8_LLSI_MODE==LLSI_MODE_SW */

#if (NUCODEGEN_LLSI8_INT_EN)

    /* Enable interrupt type */
    LLSI_EnableInt(LLSI8, NUCODEGEN_LLSI8_INT_SEL);

    /* Enable interrupt function */
    NVIC_EnableIRQ(LLSI8_IRQn);

#endif /* NUCODEGEN_LLSI8_INT_EN */

#if (NUCODEGEN_LLSI8_RESET_COMMAND_EN)

    /* Enable reset command function */
    LLSI_ENABLE_RESET_COMMAND(LLSI8);

#endif /* NUCODEGEN_LLSI8_RESET_COMMAND_EN */
}
#endif /* NUCODEGEN_LLSI8 */

#if (NUCODEGEN_LLSI9)
void LLSI9_Init()
{
    /* This function make LLSI9 module be ready to transfer */
    LLSI_Open(LLSI9, NUCODEGEN_LLSI9_LLSI_MODE, NUCODEGEN_LLSI9_OUTPUT_FORMAT, NUCODEGEN_LLSI9_BUSCLOCK, NUCODEGEN_LLSI9_TRANSFER_TIME,
              NUCODEGEN_LLSI9_T0H_TIME, NUCODEGEN_LLSI9_T1H_TIME, NUCODEGEN_LLSI9_RESET_TIME, NUCODEGEN_LLSI9_PIXEL_COUNT, NUCODEGEN_LLSI9_IDLE_OUTPUT_STATE);

#if (NUCODEGEN_LLSI9_LLSI_MODE==LLSI_MODE_SW)

    /* Set FIFO threshold */
    LLSI_SetFIFO(LLSI9, NUCODEGEN_LLSI9_TX_THRESHOLD);

#endif /* NUCODEGEN_LLSI9_LLSI_MODE==LLSI_MODE_SW */

#if (NUCODEGEN_LLSI9_INT_EN)

    /* Enable interrupt type */
    LLSI_EnableInt(LLSI9, NUCODEGEN_LLSI9_INT_SEL);

    /* Enable interrupt function */
    NVIC_EnableIRQ(LLSI9_IRQn);

#endif /* NUCODEGEN_LLSI9_INT_EN */

#if (NUCODEGEN_LLSI9_RESET_COMMAND_EN)

    /* Enable reset command function */
    LLSI_ENABLE_RESET_COMMAND(LLSI9);

#endif /* NUCODEGEN_LLSI9_RESET_COMMAND_EN */
}
#endif /* NUCODEGEN_LLSI9 */
