NUTOOL_PIN.g_cfg_chips = [
    //NUC100CN
    { name: "NUC130VE3CN", pkg: "LQFP100" },
    { name: "NUC140VE3CN", pkg: "LQFP100" },
    { name: "NUC130RC1CN", pkg: "LQFP64" },
    { name: "NUC130RD2CN", pkg: "LQFP64" },
    { name: "NUC130RE3CN", pkg: "LQFP64" },
    { name: "NUC140RC1CN", pkg: "LQFP64" },
    { name: "NUC140RD2CN", pkg: "LQFP64" },
    { name: "NUC140RE3CN", pkg: "LQFP64" },
    { name: "NUC130LC1CN", pkg: "LQFP48" },
    { name: "NUC130LD2CN", pkg: "LQFP48" },
    { name: "NUC130LE3CN", pkg: "LQFP48" },
    { name: "NUC140LC1CN", pkg: "LQFP48" },
    { name: "NUC140LD2CN", pkg: "LQFP48" },
    { name: "NUC140LE3CN", pkg: "LQFP48" },
    //NUC100DN
    { name: "NUC100VE3DN", pkg: "LQFP100" },
    { name: "NUC100RC1DN", pkg: "LQFP64" },
    { name: "NUC100RD1DN", pkg: "LQFP64" },
    { name: "NUC100RD2DN", pkg: "LQFP64" },
    { name: "NUC100RE3DN", pkg: "LQFP64" },
    { name: "NUC100LC1DN", pkg: "LQFP48" },
    { name: "NUC100LD2DN", pkg: "LQFP48" },
    { name: "NUC100LE3DN", pkg: "LQFP48" },
    { name: "NUC120VE3DN", pkg: "LQFP100" },
    { name: "NUC120RC1DN", pkg: "LQFP64" },
    { name: "NUC120RD2DN", pkg: "LQFP64" },
    { name: "NUC120RE3DN", pkg: "LQFP64" },
    { name: "NUC120LC1DN", pkg: "LQFP48" },
    { name: "NUC120LD2DN", pkg: "LQFP48" },
    { name: "NUC120LE3DN", pkg: "LQFP48" },
    //NUC121AE
    { name: "NUC121SC2AE", pkg: "LQFP64" },
    { name: "NUC121LC2AE", pkg: "LQFP48" },
    { name: "NUC121ZC2AE", pkg: "QFN33" },
    { name: "NUC125SC2AE", pkg: "LQFP64" },
    { name: "NUC125LC2AE", pkg: "LQFP48" },
    { name: "NUC125ZC2AE", pkg: "QFN33" },
    //NUC123AE
    { name: "NUC123ZD4AE0", pkg: "QFN33" },
    { name: "NUC123ZC2AE1", pkg: "QFN33" },
    { name: "NUC123SD4AE0", pkg: "LQFP64" },
    { name: "NUC123SC2AE1", pkg: "LQFP64" },
    { name: "NUC123LD4AE0", pkg: "LQFP48" },
    { name: "NUC123LC2AE1", pkg: "LQFP48" },
    //NUC123AN
    { name: "NUC123ZD4AN0", pkg: "QFN33" },
    { name: "NUC123ZC2AN1", pkg: "QFN33" },
    { name: "NUC123LD4AN0", pkg: "LQFP48" },
    { name: "NUC123LC2AN1", pkg: "LQFP48" },
    { name: "NUC123SD4AN0", pkg: "LQFP64" },
    { name: "NUC123SC2AN1", pkg: "LQFP64" },
    // NUC126
    { name: "NUC126LE4AE", pkg: "LQFP48" },
    { name: "NUC126LG4AE", pkg: "LQFP48" },
    { name: "NUC126SE4AE", pkg: "LQFP64" },
    { name: "NUC126SG4AE", pkg: "LQFP64" },
    { name: "NUC126VG4AE", pkg: "LQFP100" },
    { name: "NUC126NE4AE", pkg: "QFN48" },
    // NUC1261
    { name: "NUC1261LG4AE", pkg: "LQFP48" },
    { name: "NUC1261LE4AE", pkg: "LQFP48" },
    { name: "NUC1261NE4AE", pkg: "QFN48" },
    { name: "NUC1261SG4AE", pkg: "LQFP64" },
    { name: "NUC1261SE4AE", pkg: "LQFP64" },
    // NUC1262
    { name: "NUC1262NE4AE", pkg: "QFN48" },
    { name: "NUC1262LE4AE", pkg: "LQFP48" },
    { name: "NUC1262SE4AE", pkg: "LQFP64" },
    // NUC1263
    { name: "NUC1263ZD4AE", pkg: "QFN33" },
    { name: "NUC1263ND4AE", pkg: "QFN48" },
    { name: "NUC1263LD4AE", pkg: "LQFP48" },
    { name: "NUC1263SD4AE", pkg: "LQFP64" },
    //NUC131
    { name: "NUC131SC2AE", pkg: "LQFP64" },
    { name: "NUC131SD2AE", pkg: "LQFP64" },
    { name: "NUC131LC2AE", pkg: "LQFP48" },
    { name: "NUC131LD2AE", pkg: "LQFP48" },
    { name: "NUC131SC2AEU", pkg: "LQFP64" },
    { name: "NUC131SD2AEU", pkg: "LQFP64" },
    { name: "NUC131LC2AEU", pkg: "LQFP48" },
    { name: "NUC131LD2AEU", pkg: "LQFP48" },
    //NUC1311
    { name: "NUC1311LD2AE", pkg: "LQFP48" }
];

NUTOOL_PIN.g_cfg_pkgs = {
    "QFN33_SPD5(5*5)": [
        'PB.5','PB.4','PB.3','PB.2','PB.1','PB.0','PF.5','PF.4','PF.3','PF.2',
        'SPD5_LSCL','SPD5_LSDA','SPD5_HSCL','SPD5_HSDA','VDDIO2','nRESET','PF.0','PF.1','PC.3','PC.2',
        'PC.1','PC.0','PD.3','PD.2','VSS','LDO_CAP','VDD','PB.15','PB.14','PB.13',
        'PB.12','AVDD'
    ],
    "QFN48_SPD5(7*7)": [
        'PB.5','PB.4','PB.3','PB.2','PB.1','PB.0','PA.11','PA.10','PA.9','PA.8',
        'PF.5','PF.4','PF.3','PF.2','PA.7','PA.6','PA.5','PA.4','PA.3','PA.2',
        'SPD5_LSCL','SPD5_LSDA','SPD5_HSCL','SPD5_HSDA','VDDIO2','nRESET','PF.0','PF.1','PC.5','PC.4',
        'PC.3','PC.2','PC.1','PC.0','VSS','LDO_CAP','VDD','PC.14','PB.15','PB.14',
        'PB.13','PB.12','AVDD','VREF','AVss','PB.11','PB.7','PB.6'
    ],
    "ULQFP48(7*7)": [
        'PB.5','PB.4','PB.3','PB.2','PB.1','PB.0','PA.11','PA.10','PA.9','VDDIO0',
        'PF.5','PF.4',
        'PF.3','PF.2','PA.7','PA.6','PA.5','PA.4','PA.3','PA.2','PA.1','PA.0',
        'VDDIO1','nRESET',
        'PF.0','PF.1','PC.5','PC.4','PC.3','PC.2','PC.1','PC.0','USB_VBUS','USB_D-',
        'USB_D+','USB_VDD33_CAP',
        'VSS','LDO_CAP','VDD','PC.14','PB.15','PB.14','PB.13','PB.12','AVDD','AVss',
        'PB.7','PB.6'
    ],
    "ULQFP64(7*7)": [
        'PB.6','PB.5','PB.4','PB.3','PB.2','PB.1','PB.0','PA.11','PA.10','PA.9',
        'PA.8','PF.6','VDDIO0','PF.5','PF.4','PF.3',
        'PF.2','PC.7','PC.6','PA.7','PA.6','VSS','VDD','PD.15','PA.5','PA.4',
        'PA.3','PA.2','PA.1','PA.0','VDDIO1','nRESET',
        'PF.0','PF.1','PC.5','PC.4','PC.3','PC.2','PC.1','PC.0','PD.3','PD.2',
        'PD.1','PD.0','USB_VBUS','USB_D-','USB_D+','USB_VDD33_CAP',
        'VSS','LDO_CAP','VDD','PC.14','PB.15','PB.14','PB.13','PB.12','AVDD','VREF',
        'AVss','PB.11','PB.10','PB.9','PB.8','PB.7'
    ]
};

NUTOOL_PIN.g_cfg_OrCAD = {};

NUTOOL_PIN.g_cfg_gpios = [
    { f: ['PA.0:0', 'SPI_MOSI_MUX:2', 'SPI0_MOSI:4', 'SPI2_MOSI:5', 'I3C0_SDA:6', 'UART0_RXD:7', 'UART1_nRTS:8', 'I2C2_SDA:9', 'BPWM0_CH0:12', 'BPWM2_CH5:13', 'ACMP3_O:14', 'DAC0_ST:15']},
    { f: ['PA.1:0', 'SPI_MISO_MUX:2', 'SPI0_MISO:4', 'SPI2_MISO:5', 'I3C0_SCL:6', 'UART0_TXD:7', 'UART1_nCTS:8', 'I2C2_SCL:9', 'BPWM0_CH1:12', 'BPWM2_CH4:13', 'ACMP2_O:15']},
    { f: ['PA.2:0', 'SPI_CLK_MUX:2', 'SPI0_CLK:4', 'SPI2_CLK:5', 'I3C1_SDA:6', 'I2C0_SMBSUS:7', 'UART1_RXD:8', 'I2C1_SDA:9', 'LLSI5_OUT:10', 'BPWM0_CH2:12', 'BPWM2_CH3:13', 'ACMP3_WLAT:15']},
    { f: ['PA.3:0', 'SPI_SS_MUX:2', 'SPI0_SS:4', 'SPI2_SS:5', 'I3C1_SCL:6', 'I2C0_SMBAL:7', 'UART1_TXD:8', 'I2C1_SCL:9', 'LLSI4_OUT:10', 'BPWM0_CH3:12', 'BPWM2_CH2:13', 'CLKO:14', 'ACMP2_WLAT:15']},
    { f: ['PA.4:0', 'SPI0_I2SMCLK:4', 'I3C0_SDA:6', 'UART0_nRTS:7', 'UART0_RXD:8', 'I2C0_SDA:9', 'BPWM0_CH4:12', 'BPWM2_CH1:13', 'DAC3_ST:15']},
    { f: ['PA.5:0', 'SPI1_I2SMCLK:2', 'SPI0_I2SMCLK:4', 'SPI2_I2SMCLK:5', 'I3C0_SCL:6', 'UART0_nCTS:7', 'UART0_TXD:8', 'I2C0_SCL:9', 'BPWM0_CH5:12', 'BPWM2_CH0:13', 'DAC2_ST:15']},
    { f: ['PA.6:0', 'SPI1_SS:2', 'UART0_RXD:7', 'I2C1_SDA:8', 'BPWM3_CH5:11', 'BPWM1_CH3:12', 'ACMP1_WLAT:13', 'TM3:14', 'INT0:15']},
    { f: ['PA.7:0', 'SPI1_CLK:2', 'UART0_TXD:7', 'I2C1_SCL:8', 'BPWM3_CH4:11', 'BPWM1_CH2:12', 'ACMP0_WLAT:13', 'TM2:14', 'INT1:15']},
    { f: ['PA.8:0', 'SPI1_SS:3', 'SPI2_MOSI:4', 'UART1_RXD:7', 'BPWM0_CH3:9', 'I2C0_SCL:10', 'TM3_EXT:13', 'DAC3_ST:14', 'INT4:15']},
    { f: ['PA.9:0', 'SPI1_CLK:3', 'SPI2_MISO:4', 'UART1_TXD:7', 'BPWM0_CH2:9', 'I2C1_SDA:10', 'TM2_EXT:13', 'DAC2_ST:14']},
    { f: ['PA.10:0', 'SPI1_MISO:3', 'SPI2_CLK:4', 'I2C2_SDA:7', 'BPWM0_CH1:9', 'I2C1_SCL:10', 'TM1_EXT:13', 'DAC0_ST:14']},
    { f: ['PA.11:0', 'SPI1_MOSI:3', 'SPI2_SS:4', 'I2C2_SCL:7', 'BPWM0_CH0:9', 'TM0_EXT:13', 'DAC1_ST:14']},
    { f: ['PA.12:0']},
    { f: ['PA.13:0']},
    { f: ['PA.14:0']},
    { f: ['PA.15:0']},

    { f: ['PB.0:0', 'ADC0_CH0:1', 'VDET_P0:1', 'SPI0_SS:3', 'SPI2_I2SMCLK:4', 'UART2_RXD:7', 'SPI0_I2SMCLK:8', 'I2C1_SDA:9', 'BPWM2_CH5:11', 'BPWM3_CH5:12']},
    { f: ['PB.1:0', 'ADC0_CH1:1', 'VDET_P1:1', 'SPDH_HSA:1', 'SPI1_I2SMCLK:2', 'UART2_TXD:7', 'I2C1_SCL:9', 'BPWM2_CH4:11', 'BPWM3_CH4:12', 'TM3_EXT:13']},
    { f: ['PB.2:0', 'ADC0_CH2:1', 'ACMP0_P0:1', 'SPI1_SS:2', 'I2C1_SDA:4', 'UART1_RXD:6', 'I2C2_SDA:7', 'SPI0_I2SMCLK:8', 'BPWM2_CH3:11', 'TM3:14', 'INT3:15']},
    { f: ['PB.3:0', 'ADC0_CH3:1', 'ACMP0_P1:1', 'ACMP1_P0:1', 'SPI1_CLK:2', 'I2C1_SCL:4', 'UART1_TXD:6', 'I2C2_SCL:7', 'BPWM2_CH2:11', 'TM2:14', 'INT2:15']},
    { f: ['PB.4:0', 'ADC0_CH4:1', 'ACMP0_N:1', 'ACMP1_P1:1', 'ACMP2_P0:1', 'SPI1_MOSI:2', 'I2C0_SDA:6', 'BPWM2_CH1:11', 'LLSI5_OUT:12', 'UART2_RXD:13', 'TM1:14', 'INT1:15']},
    { f: ['PB.5:0', 'ADC0_CH5:1', 'ACMP1_N:1', 'ACMP2_P1:1', 'ACMP3_P0:1', 'SPI1_MISO:2', 'I2C0_SCL:6', 'BPWM2_CH0:11', 'LLSI4_OUT:12', 'UART2_TXD:13', 'TM0:14', 'INT0:15']},
    { f: ['PB.6:0', 'ADC0_CH6:1', 'ACMP2_N:1', 'ACMP3_P1:1', 'UART1_RXD:6', 'BPWM1_CH5:10', 'BPWM3_CH5:12', 'INT4:13', 'ACMP1_O:15']},
    { f: ['PB.7:0', 'ADC0_CH7:1', 'ACMP3_N:1', 'UART1_TXD:6', 'BPWM1_CH4:10', 'BPWM3_CH4:12', 'INT5:13', 'ACMP0_O:15']},
    { f: ['PB.8:0', 'ADC0_CH8:1', 'UART0_RXD:5', 'UART1_nRTS:6', 'I2C1_SMBSUS:7', 'I2C0_SDA:9', 'BPWM1_CH3:10']},
    { f: ['PB.9:0', 'ADC0_CH9:1', 'UART0_TXD:5', 'UART1_nCTS:6', 'I2C1_SMBAL:7', 'I2C0_SCL:9', 'BPWM1_CH2:10']},
    { f: ['PB.10:0', 'ADC0_CH10:1', 'UART0_nRTS:5', 'I2C1_SDA:7', 'BPWM1_CH1:10']},
    { f: ['PB.11:0', 'ADC0_CH11:1', 'UART0_nCTS:5', 'I2C1_SCL:7', 'SPI0_I2SMCLK:9', 'BPWM1_CH0:10']},
    { f: ['PB.12:0', 'ADC0_CH12:1', 'DAC0_OUT:1', 'ACMP0_P2:1', 'ACMP1_P2:1', 'SPI0_MOSI:4', 'UART0_RXD:6', 'I2C2_SDA:8', 'LLSI3_OUT:10', 'BPWM3_CH3:11', 'TM3_EXT:13']},
    { f: ['PB.13:0', 'ADC0_CH13:1', 'DAC1_OUT:1', 'ACMP0_P3:1', 'ACMP1_P3:1', 'SPI0_MISO:4', 'UART0_TXD:6', 'I2C2_SCL:8', 'LLSI2_OUT:10', 'BPWM3_CH2:11', 'TM2_EXT:13']},
    { f: ['PB.14:0', 'ADC0_CH14:1', 'DAC2_OUT:1', 'ACMP2_P2:1', 'ACMP3_P2:1', 'SPI0_CLK:4', 'UART0_nRTS:6', 'I2C2_SMBSUS:8', 'LLSI1_OUT:10', 'BPWM3_CH1:11', 'TM1_EXT:13', 'CLKO:14']},
    { f: ['PB.15:0', 'ADC0_CH15:1', 'DAC3_OUT:1', 'ACMP2_P3:1', 'ACMP3_P3:1', 'SPI0_SS:4', 'UART0_nCTS:6', 'I2C2_SMBAL:8', 'LLSI0_OUT:10', 'BPWM3_CH0:11', 'TM0_EXT:13']},

    { f: ['PC.0:0', 'SPI1_SS:2', 'I2C1_SDA:7', 'UART2_RXD:8', 'I2C0_SDA:9', 'BPWM3_CH5:12', 'BPWM3_CH3:13', 'ACMP1_O:14']},
    { f: ['PC.1:0', 'SPI1_CLK:2', 'I2C1_SCL:7', 'UART2_TXD:8', 'I2C0_SCL:9', 'ADC0_ST:11', 'BPWM3_CH4:12', 'BPWM2_CH1:13', 'ACMP0_O:14']},
    { f: ['PC.2:0', 'SPI1_MOSI:2', 'I2C2_SMBSUS:7', 'UART2_nCTS:8', 'I2C0_SMBSUS:9', 'I2C0_SDA:10', 'BPWM3_CH3:12', 'LLSI3_OUT:15']},
    { f: ['PC.3:0', 'SPI1_MISO:2', 'I2C2_SMBAL:7', 'UART2_nRTS:8', 'I2C0_SMBAL:9', 'I2C0_SCL:10', 'BPWM3_CH2:12', 'LLSI2_OUT:15']},
    { f: ['PC.4:0', 'SPI1_I2SMCLK:2', 'UART2_RXD:8', 'I2C1_SDA:9', 'BPWM3_CH1:12', 'LLSI1_OUT:15']},
    { f: ['PC.5:0', 'UART2_TXD:8', 'I2C1_SCL:9', 'BPWM3_CH0:12', 'LLSI0_OUT:15']},
    { f: ['PC.6:0', 'SPI1_MOSI:4', 'UART0_nRTS:7', 'I2C1_SMBSUS:8', 'BPWM3_CH3:11', 'BPWM1_CH1:12', 'TM1:14', 'INT2:15']},
    { f: ['PC.7:0', 'SPI1_MISO:4', 'UART0_nCTS:7', 'I2C1_SMBAL:8', 'BPWM3_CH2:11', 'BPWM1_CH0:12', 'TM0:14', 'INT3:15']},
    { f: ['PC.8:0']},
    { f: ['PC.9:0']},
    { f: ['PC.10:0']},
    { f: ['PC.11:0']},
    { f: ['PC.12:0']},
    { f: ['PC.13:0']},
    { f: ['PC.14:0', 'SPI1_MOSI:2', 'SPI0_I2SMCLK:4', 'TM1:13', 'DAC1_ST:15']},
    { f: ['PC.15:0']},

    { f: ['PD.0:0', 'SPI0_MOSI:4', 'TM2:14']},
    { f: ['PD.1:0', 'SPI0_MISO:4']},
    { f: ['PD.2:0', 'SPI0_CLK:4', 'UART0_RXD:9']},
    { f: ['PD.3:0', 'SPI0_SS:4', 'UART0_TXD:9']},
    { f: ['PD.4:0']},
    { f: ['PD.5:0']},
    { f: ['PD.6:0']},
    { f: ['PD.7:0']},
    { f: ['PD.8:0']},
    { f: ['PD.9:0']},
    { f: ['PD.10:0']},
    { f: ['PD.11:0']},
    { f: ['PD.12:0']},
    { f: ['PD.13:0']},
    { f: ['PD.14:0']},
    { f: ['PD.15:0', 'BPWM2_CH5:12', 'TM3:14', 'INT1:15']},

    { f: ['PE.0:0']},
    { f: ['PE.1:0']},
    { f: ['PE.2:0']},
    { f: ['PE.3:0']},
    { f: ['PE.4:0']},
    { f: ['PE.5:0']},
    { f: ['PE.6:0']},
    { f: ['PE.7:0']},
    { f: ['PE.8:0']},
    { f: ['PE.9:0']},
    { f: ['PE.10:0']},
    { f: ['PE.11:0']},
    { f: ['PE.12:0']},
    { f: ['PE.13:0']},
    { f: ['PE.14:0']},
    { f: ['PE.15:0']},

    { f: ['PF.0:0', 'UART1_TXD:2', 'I2C1_SCL:3', 'UART0_TXD:4', 'I2C2_SCL:7', 'UART2_TXD:8', 'I2C1_SMBAL:9', 'BPWM1_CH0:12', 'ACMP0_O:13', 'ICE_DAT:14']},
    { f: ['PF.1:0', 'UART1_RXD:2', 'I2C1_SDA:3', 'UART0_RXD:4', 'I2C2_SDA:7', 'UART2_RXD:8', 'I2C1_SMBSUS:9', 'BPWM1_CH1:12', 'ACMP1_O:13', 'ICE_CLK:14']},
    { f: ['PF.2:0', 'UART0_RXD:3', 'I2C0_SDA:4', 'UART1_RXD:7', 'XT1_OUT:10', 'BPWM1_CH1:11', 'ACMP3_O:13', 'INT4:15']},
    { f: ['PF.3:0', 'UART0_TXD:3', 'I2C0_SCL:4', 'UART2_RXD:7', 'BPWM0_CH3:9', 'XT1_IN:10', 'BPWM1_CH0:11', 'ACMP2_O:13']},
    { f: ['PF.4:0', 'UART2_TXD:2', 'UART2_nRTS:4', 'SPI0_MISO:5', 'BPWM2_CH1:7', 'BPWM0_CH5:8', 'I2C0_SDA:9', 'X32_OUT:10', 'BPWM2_CH5:11', 'BPWM3_CH5:12', 'ACMP3_WLAT:13']},
    { f: ['PF.5:0', 'UART2_RXD:2', 'SPI1_SS:3', 'UART2_nCTS:4', 'SPI0_CLK:5', 'BPWM2_CH0:7', 'BPWM0_CH4:8', 'I2C0_SCL:9', 'X32_IN:10', 'ADC0_ST:11', 'ACMP2_WLAT:13']},
    { f: ['PF.6:0', 'SPI0_MOSI:5', 'I2C0_SDA:10', 'LLSI3_OUT:11', 'BPWM2_CH4:12', 'CLKO:13', 'TM3:14', 'INT5:15']},
    { f: ['PF.7:0']},
    { f: ['PF.8:0']},
    { f: ['PF.9:0']},
    { f: ['PF.10:0']},
    { f: ['PF.11:0']},
    { f: ['PF.12:0']},
    { f: ['PF.13:0']},
    { f: ['PF.14:0', 'SPI0_SS:5', 'LLSI3_OUT:11', 'BPWM2_CH4:12', 'CLKO:13', 'TM3:14', 'INT5:15']},
    { f: ['PF.15:0', 'UART0_nRTS:7', 'BPWM1_CH0:12', 'TM2:13', 'CLKO:14', 'INT4:15']}
];

NUTOOL_PIN.g_cfg_gpiosDefines = [
    { f: ['PA.0', 'GPIO:SYS_GPA_MFPL_PA0MFP_GPIO@GPA_MFPL', 'SPI_MOSI_MUX:SYS_GPA_MFPL_PA0MFP_SPI_MOSI_MUX@GPA_MFPL', 'SPI0_MOSI:SYS_GPA_MFPL_PA0MFP_SPI0_MOSI@GPA_MFPL', 'SPI2_MOSI:SYS_GPA_MFPL_PA0MFP_SPI2_MOSI@GPA_MFPL', 'I3C0_SDA:SYS_GPA_MFPL_PA0MFP_I3C0_SDA@GPA_MFPL', 'UART0_RXD:SYS_GPA_MFPL_PA0MFP_UART0_RXD@GPA_MFPL', 'UART1_nRTS:SYS_GPA_MFPL_PA0MFP_UART1_nRTS@GPA_MFPL', 'I2C2_SDA:SYS_GPA_MFPL_PA0MFP_I2C2_SDA@GPA_MFPL', 'BPWM0_CH0:SYS_GPA_MFPL_PA0MFP_BPWM0_CH0@GPA_MFPL', 'BPWM2_CH5:SYS_GPA_MFPL_PA0MFP_BPWM2_CH5@GPA_MFPL', 'ACMP3_O:SYS_GPA_MFPL_PA0MFP_ACMP3_O@GPA_MFPL', 'DAC0_ST:SYS_GPA_MFPL_PA0MFP_DAC0_ST@GPA_MFPL'] },
    { f: ['PA.1', 'GPIO:SYS_GPA_MFPL_PA1MFP_GPIO@GPA_MFPL', 'SPI_MISO_MUX:SYS_GPA_MFPL_PA1MFP_SPI_MISO_MUX@GPA_MFPL', 'SPI0_MISO:SYS_GPA_MFPL_PA1MFP_SPI0_MISO@GPA_MFPL', 'SPI2_MISO:SYS_GPA_MFPL_PA1MFP_SPI2_MISO@GPA_MFPL', 'I3C0_SCL:SYS_GPA_MFPL_PA1MFP_I3C0_SCL@GPA_MFPL', 'UART0_TXD:SYS_GPA_MFPL_PA1MFP_UART0_TXD@GPA_MFPL', 'UART1_nCTS:SYS_GPA_MFPL_PA1MFP_UART1_nCTS@GPA_MFPL', 'I2C2_SCL:SYS_GPA_MFPL_PA1MFP_I2C2_SCL@GPA_MFPL', 'BPWM0_CH1:SYS_GPA_MFPL_PA1MFP_BPWM0_CH1@GPA_MFPL', 'BPWM2_CH4:SYS_GPA_MFPL_PA1MFP_BPWM2_CH4@GPA_MFPL', 'ACMP2_O:SYS_GPA_MFPL_PA1MFP_ACMP2_O@GPA_MFPL'] },
    { f: ['PA.2', 'GPIO:SYS_GPA_MFPL_PA2MFP_GPIO@GPA_MFPL', 'SPI_CLK_MUX:SYS_GPA_MFPL_PA2MFP_SPI_CLK_MUX@GPA_MFPL', 'SPI0_CLK:SYS_GPA_MFPL_PA2MFP_SPI0_CLK@GPA_MFPL', 'SPI2_CLK:SYS_GPA_MFPL_PA2MFP_SPI2_CLK@GPA_MFPL', 'I3C1_SDA:SYS_GPA_MFPL_PA2MFP_I3C1_SDA@GPA_MFPL', 'I2C0_SMBSUS:SYS_GPA_MFPL_PA2MFP_I2C0_SMBSUS@GPA_MFPL', 'UART1_RXD:SYS_GPA_MFPL_PA2MFP_UART1_RXD@GPA_MFPL', 'I2C1_SDA:SYS_GPA_MFPL_PA2MFP_I2C1_SDA@GPA_MFPL', 'LLSI5_OUT:SYS_GPA_MFPL_PA2MFP_LLSI5_OUT@GPA_MFPL', 'BPWM0_CH2:SYS_GPA_MFPL_PA2MFP_BPWM0_CH2@GPA_MFPL', 'BPWM2_CH3:SYS_GPA_MFPL_PA2MFP_BPWM2_CH3@GPA_MFPL', 'ACMP3_WLAT:SYS_GPA_MFPL_PA2MFP_ACMP3_WLAT@GPA_MFPL'] },
    { f: ['PA.3', 'GPIO:SYS_GPA_MFPL_PA3MFP_GPIO@GPA_MFPL', 'SPI_SS_MUX:SYS_GPA_MFPL_PA3MFP_SPI_SS_MUX@GPA_MFPL', 'SPI0_SS:SYS_GPA_MFPL_PA3MFP_SPI0_SS@GPA_MFPL', 'SPI2_SS:SYS_GPA_MFPL_PA3MFP_SPI2_SS@GPA_MFPL', 'I3C1_SCL:SYS_GPA_MFPL_PA3MFP_I3C1_SCL@GPA_MFPL', 'I2C0_SMBAL:SYS_GPA_MFPL_PA3MFP_I2C0_SMBAL@GPA_MFPL', 'UART1_TXD:SYS_GPA_MFPL_PA3MFP_UART1_TXD@GPA_MFPL', 'I2C1_SCL:SYS_GPA_MFPL_PA3MFP_I2C1_SCL@GPA_MFPL', 'LLSI4_OUT:SYS_GPA_MFPL_PA3MFP_LLSI4_OUT@GPA_MFPL', 'BPWM0_CH3:SYS_GPA_MFPL_PA3MFP_BPWM0_CH3@GPA_MFPL', 'BPWM2_CH2:SYS_GPA_MFPL_PA3MFP_BPWM2_CH2@GPA_MFPL', 'CLKO:SYS_GPA_MFPL_PA3MFP_CLKO@GPA_MFPL', 'ACMP2_WLAT:SYS_GPA_MFPL_PA3MFP_ACMP2_WLAT@GPA_MFPL'] },
    { f: ['PA.4', 'GPIO:SYS_GPA_MFPL_PA4MFP_GPIO@GPA_MFPL', 'SPI0_I2SMCLK:SYS_GPA_MFPL_PA4MFP_SPI0_I2SMCLK@GPA_MFPL', 'I3C0_SDA:SYS_GPA_MFPL_PA4MFP_I3C0_SDA@GPA_MFPL', 'UART0_nRTS:SYS_GPA_MFPL_PA4MFP_UART0_nRTS@GPA_MFPL', 'UART0_RXD:SYS_GPA_MFPL_PA4MFP_UART0_RXD@GPA_MFPL', 'I2C0_SDA:SYS_GPA_MFPL_PA4MFP_I2C0_SDA@GPA_MFPL', 'BPWM0_CH4:SYS_GPA_MFPL_PA4MFP_BPWM0_CH4@GPA_MFPL', 'BPWM2_CH1:SYS_GPA_MFPL_PA4MFP_BPWM2_CH1@GPA_MFPL', 'DAC3_ST:SYS_GPA_MFPL_PA4MFP_DAC3_ST@GPA_MFPL'] },
    { f: ['PA.5', 'GPIO:SYS_GPA_MFPL_PA5MFP_GPIO@GPA_MFPL', 'SPI1_I2SMCLK:SYS_GPA_MFPL_PA5MFP_SPI1_I2SMCLK@GPA_MFPL', 'SPI0_I2SMCLK:SYS_GPA_MFPL_PA5MFP_SPI0_I2SMCLK@GPA_MFPL', 'SPI2_I2SMCLK:SYS_GPA_MFPL_PA5MFP_SPI2_I2SMCLK@GPA_MFPL', 'I3C0_SCL:SYS_GPA_MFPL_PA5MFP_I3C0_SCL@GPA_MFPL', 'UART0_nCTS:SYS_GPA_MFPL_PA5MFP_UART0_nCTS@GPA_MFPL', 'UART0_TXD:SYS_GPA_MFPL_PA5MFP_UART0_TXD@GPA_MFPL', 'I2C0_SCL:SYS_GPA_MFPL_PA5MFP_I2C0_SCL@GPA_MFPL', 'BPWM0_CH5:SYS_GPA_MFPL_PA5MFP_BPWM0_CH5@GPA_MFPL', 'BPWM2_CH0:SYS_GPA_MFPL_PA5MFP_BPWM2_CH0@GPA_MFPL', 'DAC2_ST:SYS_GPA_MFPL_PA5MFP_DAC2_ST@GPA_MFPL'] },
    { f: ['PA.6', 'GPIO:SYS_GPA_MFPL_PA6MFP_GPIO@GPA_MFPL', 'SPI1_SS:SYS_GPA_MFPL_PA6MFP_SPI1_SS@GPA_MFPL', 'UART0_RXD:SYS_GPA_MFPL_PA6MFP_UART0_RXD@GPA_MFPL', 'I2C1_SDA:SYS_GPA_MFPL_PA6MFP_I2C1_SDA@GPA_MFPL', 'BPWM3_CH5:SYS_GPA_MFPL_PA6MFP_BPWM3_CH5@GPA_MFPL', 'BPWM1_CH3:SYS_GPA_MFPL_PA6MFP_BPWM1_CH3@GPA_MFPL', 'ACMP1_WLAT:SYS_GPA_MFPL_PA6MFP_ACMP1_WLAT@GPA_MFPL', 'TM3:SYS_GPA_MFPL_PA6MFP_TM3@GPA_MFPL', 'INT0:SYS_GPA_MFPL_PA6MFP_INT0@GPA_MFPL'] },
    { f: ['PA.7', 'GPIO:SYS_GPA_MFPL_PA7MFP_GPIO@GPA_MFPL', 'SPI1_CLK:SYS_GPA_MFPL_PA7MFP_SPI1_CLK@GPA_MFPL', 'UART0_TXD:SYS_GPA_MFPL_PA7MFP_UART0_TXD@GPA_MFPL', 'I2C1_SCL:SYS_GPA_MFPL_PA7MFP_I2C1_SCL@GPA_MFPL', 'BPWM3_CH4:SYS_GPA_MFPL_PA7MFP_BPWM3_CH4@GPA_MFPL', 'BPWM1_CH2:SYS_GPA_MFPL_PA7MFP_BPWM1_CH2@GPA_MFPL', 'ACMP0_WLAT:SYS_GPA_MFPL_PA7MFP_ACMP0_WLAT@GPA_MFPL', 'TM2:SYS_GPA_MFPL_PA7MFP_TM2@GPA_MFPL', 'INT1:SYS_GPA_MFPL_PA7MFP_INT1@GPA_MFPL'] },
    { f: ['PA.8', 'GPIO:SYS_GPA_MFPH_PA8MFP_GPIO@GPA_MFPH', 'SPI1_SS:SYS_GPA_MFPH_PA8MFP_SPI1_SS@GPA_MFPH', 'SPI2_MOSI:SYS_GPA_MFPH_PA8MFP_SPI2_MOSI@GPA_MFPH', 'UART1_RXD:SYS_GPA_MFPH_PA8MFP_UART1_RXD@GPA_MFPH', 'BPWM0_CH3:SYS_GPA_MFPH_PA8MFP_BPWM0_CH3@GPA_MFPH', 'I2C0_SCL:SYS_GPA_MFPH_PA8MFP_I2C0_SCL@GPA_MFPH', 'TM3_EXT:SYS_GPA_MFPH_PA8MFP_TM3_EXT@GPA_MFPH', 'DAC3_ST:SYS_GPA_MFPH_PA8MFP_DAC3_ST@GPA_MFPH', 'INT4:SYS_GPA_MFPH_PA8MFP_INT4@GPA_MFPH'] },
    { f: ['PA.9', 'GPIO:SYS_GPA_MFPH_PA9MFP_GPIO@GPA_MFPH', 'SPI1_CLK:SYS_GPA_MFPH_PA9MFP_SPI1_CLK@GPA_MFPH', 'SPI2_MISO:SYS_GPA_MFPH_PA9MFP_SPI2_MISO@GPA_MFPH', 'UART1_TXD:SYS_GPA_MFPH_PA9MFP_UART1_TXD@GPA_MFPH', 'BPWM0_CH2:SYS_GPA_MFPH_PA9MFP_BPWM0_CH2@GPA_MFPH', 'I2C1_SDA:SYS_GPA_MFPH_PA9MFP_I2C1_SDA@GPA_MFPH', 'TM2_EXT:SYS_GPA_MFPH_PA9MFP_TM2_EXT@GPA_MFPH', 'DAC2_ST:SYS_GPA_MFPH_PA9MFP_DAC2_ST@GPA_MFPH'] },
    { f: ['PA.10', 'GPIO:SYS_GPA_MFPH_PA10MFP_GPIO@GPA_MFPH', 'SPI1_MISO:SYS_GPA_MFPH_PA10MFP_SPI1_MISO@GPA_MFPH', 'SPI2_CLK:SYS_GPA_MFPH_PA10MFP_SPI2_CLK@GPA_MFPH', 'I2C2_SDA:SYS_GPA_MFPH_PA10MFP_I2C2_SDA@GPA_MFPH', 'BPWM0_CH1:SYS_GPA_MFPH_PA10MFP_BPWM0_CH1@GPA_MFPH', 'I2C1_SCL:SYS_GPA_MFPH_PA10MFP_I2C1_SCL@GPA_MFPH', 'TM1_EXT:SYS_GPA_MFPH_PA10MFP_TM1_EXT@GPA_MFPH', 'DAC0_ST:SYS_GPA_MFPH_PA10MFP_DAC0_ST@GPA_MFPH'] },
    { f: ['PA.11', 'GPIO:SYS_GPA_MFPH_PA11MFP_GPIO@GPA_MFPH', 'SPI1_MOSI:SYS_GPA_MFPH_PA11MFP_SPI1_MOSI@GPA_MFPH', 'SPI2_SS:SYS_GPA_MFPH_PA11MFP_SPI2_SS@GPA_MFPH', 'I2C2_SCL:SYS_GPA_MFPH_PA11MFP_I2C2_SCL@GPA_MFPH', 'BPWM0_CH0:SYS_GPA_MFPH_PA11MFP_BPWM0_CH0@GPA_MFPH', 'TM0_EXT:SYS_GPA_MFPH_PA11MFP_TM0_EXT@GPA_MFPH', 'DAC1_ST:SYS_GPA_MFPH_PA11MFP_DAC1_ST@GPA_MFPH'] },

    { f: ['PB.0', 'GPIO:SYS_GPB_MFPL_PB0MFP_GPIO@GPB_MFPL', 'ADC0_CH0:SYS_GPB_MFPL_PB0MFP_ADC0_CH0@GPB_MFPL', 'VDET_P0:SYS_GPB_MFPL_PB0MFP_VDET_P0@GPB_MFPL', 'SPI0_SS:SYS_GPB_MFPL_PB0MFP_SPI0_SS@GPB_MFPL', 'SPI2_I2SMCLK:SYS_GPB_MFPL_PB0MFP_SPI2_I2SMCLK@GPB_MFPL', 'UART2_RXD:SYS_GPB_MFPL_PB0MFP_UART2_RXD@GPB_MFPL', 'SPI0_I2SMCLK:SYS_GPB_MFPL_PB0MFP_SPI0_I2SMCLK@GPB_MFPL', 'I2C1_SDA:SYS_GPB_MFPL_PB0MFP_I2C1_SDA@GPB_MFPL', 'BPWM2_CH5:SYS_GPB_MFPL_PB0MFP_BPWM2_CH5@GPB_MFPL', 'BPWM3_CH5:SYS_GPB_MFPL_PB0MFP_BPWM3_CH5@GPB_MFPL'] },
    { f: ['PB.1', 'GPIO:SYS_GPB_MFPL_PB1MFP_GPIO@GPB_MFPL', 'ADC0_CH1:SYS_GPB_MFPL_PB1MFP_ADC0_CH1@GPB_MFPL', 'VDET_P1:SYS_GPB_MFPL_PB1MFP_VDET_P1@GPB_MFPL', 'SPDH_HSA:SYS_GPB_MFPL_PB1MFP_SPDH_HSA@GPB_MFPL', 'SPI1_I2SMCLK:SYS_GPB_MFPL_PB1MFP_SPI1_I2SMCLK@GPB_MFPL', 'UART2_TXD:SYS_GPB_MFPL_PB1MFP_UART2_TXD@GPB_MFPL', 'I2C1_SCL:SYS_GPB_MFPL_PB1MFP_I2C1_SCL@GPB_MFPL', 'BPWM2_CH4:SYS_GPB_MFPL_PB1MFP_BPWM2_CH4@GPB_MFPL', 'BPWM3_CH4:SYS_GPB_MFPL_PB1MFP_BPWM3_CH4@GPB_MFPL', 'TM3_EXT:SYS_GPB_MFPL_PB1MFP_TM3_EXT@GPB_MFPL'] },
    { f: ['PB.2', 'GPIO:SYS_GPB_MFPL_PB2MFP_GPIO@GPB_MFPL', 'ADC0_CH2:SYS_GPB_MFPL_PB2MFP_ADC0_CH2@GPB_MFPL', 'ACMP0_P0:SYS_GPB_MFPL_PB2MFP_ACMP0_P0@GPB_MFPL', 'SPI1_SS:SYS_GPB_MFPL_PB2MFP_SPI1_SS@GPB_MFPL', 'I2C1_SDA:SYS_GPB_MFPL_PB2MFP_I2C1_SDA@GPB_MFPL', 'UART1_RXD:SYS_GPB_MFPL_PB2MFP_UART1_RXD@GPB_MFPL', 'I2C2_SDA:SYS_GPB_MFPL_PB2MFP_I2C2_SDA@GPB_MFPL', 'SPI0_I2SMCLK:SYS_GPB_MFPL_PB2MFP_SPI0_I2SMCLK@GPB_MFPL', 'BPWM2_CH3:SYS_GPB_MFPL_PB2MFP_BPWM2_CH3@GPB_MFPL', 'TM3:SYS_GPB_MFPL_PB2MFP_TM3@GPB_MFPL', 'INT3:SYS_GPB_MFPL_PB2MFP_INT3@GPB_MFPL'] },
    { f: ['PB.3', 'GPIO:SYS_GPB_MFPL_PB3MFP_GPIO@GPB_MFPL', 'ADC0_CH3:SYS_GPB_MFPL_PB3MFP_ADC0_CH3@GPB_MFPL', 'ACMP0_P1:SYS_GPB_MFPL_PB3MFP_ACMP0_P1@GPB_MFPL', 'ACMP1_P0:SYS_GPB_MFPL_PB3MFP_ACMP1_P0@GPB_MFPL', 'SPI1_CLK:SYS_GPB_MFPL_PB3MFP_SPI1_CLK@GPB_MFPL', 'I2C1_SCL:SYS_GPB_MFPL_PB3MFP_I2C1_SCL@GPB_MFPL', 'UART1_TXD:SYS_GPB_MFPL_PB3MFP_UART1_TXD@GPB_MFPL', 'I2C2_SCL:SYS_GPB_MFPL_PB3MFP_I2C2_SCL@GPB_MFPL', 'BPWM2_CH2:SYS_GPB_MFPL_PB3MFP_BPWM2_CH2@GPB_MFPL', 'TM2:SYS_GPB_MFPL_PB3MFP_TM2@GPB_MFPL', 'INT2:SYS_GPB_MFPL_PB3MFP_INT2@GPB_MFPL'] },
    { f: ['PB.4', 'GPIO:SYS_GPB_MFPL_PB4MFP_GPIO@GPB_MFPL', 'ADC0_CH4:SYS_GPB_MFPL_PB4MFP_ADC0_CH4@GPB_MFPL', 'ACMP0_N:SYS_GPB_MFPL_PB4MFP_ACMP0_N@GPB_MFPL', 'ACMP1_P1:SYS_GPB_MFPL_PB4MFP_ACMP1_P1@GPB_MFPL', 'ACMP2_P0:SYS_GPB_MFPL_PB4MFP_ACMP2_P0@GPB_MFPL', 'SPI1_MOSI:SYS_GPB_MFPL_PB4MFP_SPI1_MOSI@GPB_MFPL', 'I2C0_SDA:SYS_GPB_MFPL_PB4MFP_I2C0_SDA@GPB_MFPL', 'BPWM2_CH1:SYS_GPB_MFPL_PB4MFP_BPWM2_CH1@GPB_MFPL', 'LLSI5_OUT:SYS_GPB_MFPL_PB4MFP_LLSI5_OUT@GPB_MFPL', 'UART2_RXD:SYS_GPB_MFPL_PB4MFP_UART2_RXD@GPB_MFPL', 'TM1:SYS_GPB_MFPL_PB4MFP_TM1@GPB_MFPL', 'INT1:SYS_GPB_MFPL_PB4MFP_INT1@GPB_MFPL'] },
    { f: ['PB.5', 'GPIO:SYS_GPB_MFPL_PB5MFP_GPIO@GPB_MFPL', 'ADC0_CH5:SYS_GPB_MFPL_PB5MFP_ADC0_CH5@GPB_MFPL', 'ACMP1_N:SYS_GPB_MFPL_PB5MFP_ACMP1_N@GPB_MFPL', 'ACMP2_P1:SYS_GPB_MFPL_PB5MFP_ACMP2_P1@GPB_MFPL', 'ACMP3_P0:SYS_GPB_MFPL_PB5MFP_ACMP3_P0@GPB_MFPL', 'SPI1_MISO:SYS_GPB_MFPL_PB5MFP_SPI1_MISO@GPB_MFPL', 'I2C0_SCL:SYS_GPB_MFPL_PB5MFP_I2C0_SCL@GPB_MFPL', 'BPWM2_CH0:SYS_GPB_MFPL_PB5MFP_BPWM2_CH0@GPB_MFPL', 'LLSI4_OUT:SYS_GPB_MFPL_PB5MFP_LLSI4_OUT@GPB_MFPL', 'UART2_TXD:SYS_GPB_MFPL_PB5MFP_UART2_TXD@GPB_MFPL', 'TM0:SYS_GPB_MFPL_PB5MFP_TM0@GPB_MFPL', 'INT0:SYS_GPB_MFPL_PB5MFP_INT0@GPB_MFPL'] },
    { f: ['PB.6', 'GPIO:SYS_GPB_MFPL_PB6MFP_GPIO@GPB_MFPL', 'ADC0_CH6:SYS_GPB_MFPL_PB6MFP_ADC0_CH6@GPB_MFPL', 'ACMP2_N:SYS_GPB_MFPL_PB6MFP_ACMP2_N@GPB_MFPL', 'ACMP3_P1:SYS_GPB_MFPL_PB6MFP_ACMP3_P1@GPB_MFPL', 'UART1_RXD:SYS_GPB_MFPL_PB6MFP_UART1_RXD@GPB_MFPL', 'BPWM1_CH5:SYS_GPB_MFPL_PB6MFP_BPWM1_CH5@GPB_MFPL', 'BPWM3_CH5:SYS_GPB_MFPL_PB6MFP_BPWM3_CH5@GPB_MFPL', 'INT4:SYS_GPB_MFPL_PB6MFP_INT4@GPB_MFPL', 'ACMP1_O:SYS_GPB_MFPL_PB6MFP_ACMP1_O@GPB_MFPL'] },
    { f: ['PB.7', 'GPIO:SYS_GPB_MFPL_PB7MFP_GPIO@GPB_MFPL', 'ADC0_CH7:SYS_GPB_MFPL_PB7MFP_ADC0_CH7@GPB_MFPL', 'ACMP3_N:SYS_GPB_MFPL_PB7MFP_ACMP3_N@GPB_MFPL', 'UART1_TXD:SYS_GPB_MFPL_PB7MFP_UART1_TXD@GPB_MFPL', 'BPWM1_CH4:SYS_GPB_MFPL_PB7MFP_BPWM1_CH4@GPB_MFPL', 'BPWM3_CH4:SYS_GPB_MFPL_PB7MFP_BPWM3_CH4@GPB_MFPL', 'INT5:SYS_GPB_MFPL_PB7MFP_INT5@GPB_MFPL', 'ACMP0_O:SYS_GPB_MFPL_PB7MFP_ACMP0_O@GPB_MFPL'] },
    { f: ['PB.8', 'GPIO:SYS_GPB_MFPH_PB8MFP_GPIO@GPB_MFPH', 'ADC0_CH8:SYS_GPB_MFPH_PB8MFP_ADC0_CH8@GPB_MFPH', 'UART0_RXD:SYS_GPB_MFPH_PB8MFP_UART0_RXD@GPB_MFPH', 'UART1_nRTS:SYS_GPB_MFPH_PB8MFP_UART1_nRTS@GPB_MFPH', 'I2C1_SMBSUS:SYS_GPB_MFPH_PB8MFP_I2C1_SMBSUS@GPB_MFPH', 'I2C0_SDA:SYS_GPB_MFPH_PB8MFP_I2C0_SDA@GPB_MFPH', 'BPWM1_CH3:SYS_GPB_MFPH_PB8MFP_BPWM1_CH3@GPB_MFPH'] },
    { f: ['PB.9', 'GPIO:SYS_GPB_MFPH_PB9MFP_GPIO@GPB_MFPH', 'ADC0_CH9:SYS_GPB_MFPH_PB9MFP_ADC0_CH9@GPB_MFPH', 'UART0_TXD:SYS_GPB_MFPH_PB9MFP_UART0_TXD@GPB_MFPH', 'UART1_nCTS:SYS_GPB_MFPH_PB9MFP_UART1_nCTS@GPB_MFPH', 'I2C1_SMBAL:SYS_GPB_MFPH_PB9MFP_I2C1_SMBAL@GPB_MFPH', 'I2C0_SCL:SYS_GPB_MFPH_PB9MFP_I2C0_SCL@GPB_MFPH', 'BPWM1_CH2:SYS_GPB_MFPH_PB9MFP_BPWM1_CH2@GPB_MFPH'] },
    { f: ['PB.10', 'GPIO:SYS_GPB_MFPH_PB10MFP_GPIO@GPB_MFPH', 'ADC0_CH10:SYS_GPB_MFPH_PB10MFP_ADC0_CH10@GPB_MFPH', 'UART0_nRTS:SYS_GPB_MFPH_PB10MFP_UART0_nRTS@GPB_MFPH', 'I2C1_SDA:SYS_GPB_MFPH_PB10MFP_I2C1_SDA@GPB_MFPH', 'BPWM1_CH1:SYS_GPB_MFPH_PB10MFP_BPWM1_CH1@GPB_MFPH'] },
    { f: ['PB.11', 'GPIO:SYS_GPB_MFPH_PB11MFP_GPIO@GPB_MFPH', 'ADC0_CH11:SYS_GPB_MFPH_PB11MFP_ADC0_CH11@GPB_MFPH', 'UART0_nCTS:SYS_GPB_MFPH_PB11MFP_UART0_nCTS@GPB_MFPH', 'I2C1_SCL:SYS_GPB_MFPH_PB11MFP_I2C1_SCL@GPB_MFPH', 'SPI0_I2SMCLK:SYS_GPB_MFPH_PB11MFP_SPI0_I2SMCLK@GPB_MFPH', 'BPWM1_CH0:SYS_GPB_MFPH_PB11MFP_BPWM1_CH0@GPB_MFPH'] },
    { f: ['PB.12', 'GPIO:SYS_GPB_MFPH_PB12MFP_GPIO@GPB_MFPH', 'ADC0_CH12:SYS_GPB_MFPH_PB12MFP_ADC0_CH12@GPB_MFPH', 'DAC0_OUT:SYS_GPB_MFPH_PB12MFP_DAC0_OUT@GPB_MFPH', 'ACMP0_P2:SYS_GPB_MFPH_PB12MFP_ACMP0_P2@GPB_MFPH', 'ACMP1_P2:SYS_GPB_MFPH_PB12MFP_ACMP1_P2@GPB_MFPH', 'SPI0_MOSI:SYS_GPB_MFPH_PB12MFP_SPI0_MOSI@GPB_MFPH', 'UART0_RXD:SYS_GPB_MFPH_PB12MFP_UART0_RXD@GPB_MFPH', 'I2C2_SDA:SYS_GPB_MFPH_PB12MFP_I2C2_SDA@GPB_MFPH', 'LLSI3_OUT:SYS_GPB_MFPH_PB12MFP_LLSI3_OUT@GPB_MFPH', 'BPWM3_CH3:SYS_GPB_MFPH_PB12MFP_BPWM3_CH3@GPB_MFPH', 'TM3_EXT:SYS_GPB_MFPH_PB12MFP_TM3_EXT@GPB_MFPH'] },
    { f: ['PB.13', 'GPIO:SYS_GPB_MFPH_PB13MFP_GPIO@GPB_MFPH', 'ADC0_CH13:SYS_GPB_MFPH_PB13MFP_ADC0_CH13@GPB_MFPH', 'DAC1_OUT:SYS_GPB_MFPH_PB13MFP_DAC1_OUT@GPB_MFPH', 'ACMP0_P3:SYS_GPB_MFPH_PB13MFP_ACMP0_P3@GPB_MFPH', 'ACMP1_P3:SYS_GPB_MFPH_PB13MFP_ACMP1_P3@GPB_MFPH', 'SPI0_MISO:SYS_GPB_MFPH_PB13MFP_SPI0_MISO@GPB_MFPH', 'UART0_TXD:SYS_GPB_MFPH_PB13MFP_UART0_TXD@GPB_MFPH', 'I2C2_SCL:SYS_GPB_MFPH_PB13MFP_I2C2_SCL@GPB_MFPH', 'LLSI2_OUT:SYS_GPB_MFPH_PB13MFP_LLSI2_OUT@GPB_MFPH', 'BPWM3_CH2:SYS_GPB_MFPH_PB13MFP_BPWM3_CH2@GPB_MFPH', 'TM2_EXT:SYS_GPB_MFPH_PB13MFP_TM2_EXT@GPB_MFPH'] },
    { f: ['PB.14', 'GPIO:SYS_GPB_MFPH_PB14MFP_GPIO@GPB_MFPH', 'ADC0_CH14:SYS_GPB_MFPH_PB14MFP_ADC0_CH14@GPB_MFPH', 'DAC2_OUT:SYS_GPB_MFPH_PB14MFP_DAC2_OUT@GPB_MFPH', 'ACMP2_P2:SYS_GPB_MFPH_PB14MFP_ACMP2_P2@GPB_MFPH', 'ACMP3_P2:SYS_GPB_MFPH_PB14MFP_ACMP3_P2@GPB_MFPH', 'SPI0_CLK:SYS_GPB_MFPH_PB14MFP_SPI0_CLK@GPB_MFPH', 'UART0_nRTS:SYS_GPB_MFPH_PB14MFP_UART0_nRTS@GPB_MFPH', 'I2C2_SMBSUS:SYS_GPB_MFPH_PB14MFP_I2C2_SMBSUS@GPB_MFPH', 'LLSI1_OUT:SYS_GPB_MFPH_PB14MFP_LLSI1_OUT@GPB_MFPH', 'BPWM3_CH1:SYS_GPB_MFPH_PB14MFP_BPWM3_CH1@GPB_MFPH', 'TM1_EXT:SYS_GPB_MFPH_PB14MFP_TM1_EXT@GPB_MFPH', 'CLKO:SYS_GPB_MFPH_PB14MFP_CLKO@GPB_MFPH'] },
    { f: ['PB.15', 'GPIO:SYS_GPB_MFPH_PB15MFP_GPIO@GPB_MFPH', 'ADC0_CH15:SYS_GPB_MFPH_PB15MFP_ADC0_CH15@GPB_MFPH', 'DAC3_OUT:SYS_GPB_MFPH_PB15MFP_DAC3_OUT@GPB_MFPH', 'ACMP2_P3:SYS_GPB_MFPH_PB15MFP_ACMP2_P3@GPB_MFPH', 'ACMP3_P3:SYS_GPB_MFPH_PB15MFP_ACMP3_P3@GPB_MFPH', 'SPI0_SS:SYS_GPB_MFPH_PB15MFP_SPI0_SS@GPB_MFPH', 'UART0_nCTS:SYS_GPB_MFPH_PB15MFP_UART0_nCTS@GPB_MFPH', 'I2C2_SMBAL:SYS_GPB_MFPH_PB15MFP_I2C2_SMBAL@GPB_MFPH', 'LLSI0_OUT:SYS_GPB_MFPH_PB15MFP_LLSI0_OUT@GPB_MFPH', 'BPWM3_CH0:SYS_GPB_MFPH_PB15MFP_BPWM3_CH0@GPB_MFPH', 'TM0_EXT:SYS_GPB_MFPH_PB15MFP_TM0_EXT@GPB_MFPH'] },

    { f: ['PC.0', 'GPIO:SYS_GPC_MFPL_PC0MFP_GPIO@GPC_MFPL', 'SPI1_SS:SYS_GPC_MFPL_PC0MFP_SPI1_SS@GPC_MFPL', 'I2C1_SDA:SYS_GPC_MFPL_PC0MFP_I2C1_SDA@GPC_MFPL', 'UART2_RXD:SYS_GPC_MFPL_PC0MFP_UART2_RXD@GPC_MFPL', 'I2C0_SDA:SYS_GPC_MFPL_PC0MFP_I2C0_SDA@GPC_MFPL', 'BPWM3_CH5:SYS_GPC_MFPL_PC0MFP_BPWM3_CH5@GPC_MFPL', 'BPWM3_CH3:SYS_GPC_MFPL_PC0MFP_BPWM3_CH3@GPC_MFPL', 'ACMP1_O:SYS_GPC_MFPL_PC0MFP_ACMP1_O@GPC_MFPL'] },
    { f: ['PC.1', 'GPIO:SYS_GPC_MFPL_PC1MFP_GPIO@GPC_MFPL', 'SPI1_CLK:SYS_GPC_MFPL_PC1MFP_SPI1_CLK@GPC_MFPL', 'I2C1_SCL:SYS_GPC_MFPL_PC1MFP_I2C1_SCL@GPC_MFPL', 'UART2_TXD:SYS_GPC_MFPL_PC1MFP_UART2_TXD@GPC_MFPL', 'I2C0_SCL:SYS_GPC_MFPL_PC1MFP_I2C0_SCL@GPC_MFPL', 'ADC0_ST:SYS_GPC_MFPL_PC1MFP_ADC0_ST@GPC_MFPL', 'BPWM3_CH4:SYS_GPC_MFPL_PC1MFP_BPWM3_CH4@GPC_MFPL', 'BPWM2_CH1:SYS_GPC_MFPL_PC1MFP_BPWM2_CH1@GPC_MFPL', 'ACMP0_O:SYS_GPC_MFPL_PC1MFP_ACMP0_O@GPC_MFPL'] },
    { f: ['PC.2', 'GPIO:SYS_GPC_MFPL_PC2MFP_GPIO@GPC_MFPL', 'SPI1_MOSI:SYS_GPC_MFPL_PC2MFP_SPI1_MOSI@GPC_MFPL', 'I2C2_SMBSUS:SYS_GPC_MFPL_PC2MFP_I2C2_SMBSUS@GPC_MFPL', 'UART2_nCTS:SYS_GPC_MFPL_PC2MFP_UART2_nCTS@GPC_MFPL', 'I2C0_SMBSUS:SYS_GPC_MFPL_PC2MFP_I2C0_SMBSUS@GPC_MFPL', 'I2C0_SDA:SYS_GPC_MFPL_PC2MFP_I2C0_SDA@GPC_MFPL', 'BPWM3_CH3:SYS_GPC_MFPL_PC2MFP_BPWM3_CH3@GPC_MFPL', 'LLSI3_OUT:SYS_GPC_MFPL_PC2MFP_LLSI3_OUT@GPC_MFPL'] },
    { f: ['PC.3', 'GPIO:SYS_GPC_MFPL_PC3MFP_GPIO@GPC_MFPL', 'SPI1_MISO:SYS_GPC_MFPL_PC3MFP_SPI1_MISO@GPC_MFPL', 'I2C2_SMBAL:SYS_GPC_MFPL_PC3MFP_I2C2_SMBAL@GPC_MFPL', 'UART2_nRTS:SYS_GPC_MFPL_PC3MFP_UART2_nRTS@GPC_MFPL', 'I2C0_SMBAL:SYS_GPC_MFPL_PC3MFP_I2C0_SMBAL@GPC_MFPL', 'I2C0_SCL:SYS_GPC_MFPL_PC3MFP_I2C0_SCL@GPC_MFPL', 'BPWM3_CH2:SYS_GPC_MFPL_PC3MFP_BPWM3_CH2@GPC_MFPL', 'LLSI2_OUT:SYS_GPC_MFPL_PC3MFP_LLSI2_OUT@GPC_MFPL'] },
    { f: ['PC.4', 'GPIO:SYS_GPC_MFPL_PC4MFP_GPIO@GPC_MFPL', 'SPI1_I2SMCLK:SYS_GPC_MFPL_PC4MFP_SPI1_I2SMCLK@GPC_MFPL', 'UART2_RXD:SYS_GPC_MFPL_PC4MFP_UART2_RXD@GPC_MFPL', 'I2C1_SDA:SYS_GPC_MFPL_PC4MFP_I2C1_SDA@GPC_MFPL', 'BPWM3_CH1:SYS_GPC_MFPL_PC4MFP_BPWM3_CH1@GPC_MFPL', 'LLSI1_OUT:SYS_GPC_MFPL_PC4MFP_LLSI1_OUT@GPC_MFPL'] },
    { f: ['PC.5', 'GPIO:SYS_GPC_MFPL_PC5MFP_GPIO@GPC_MFPL', 'UART2_TXD:SYS_GPC_MFPL_PC5MFP_UART2_TXD@GPC_MFPL', 'I2C1_SCL:SYS_GPC_MFPL_PC5MFP_I2C1_SCL@GPC_MFPL', 'BPWM3_CH0:SYS_GPC_MFPL_PC5MFP_BPWM3_CH0@GPC_MFPL', 'LLSI0_OUT:SYS_GPC_MFPL_PC5MFP_LLSI0_OUT@GPC_MFPL'] },
    { f: ['PC.6', 'GPIO:SYS_GPC_MFPL_PC6MFP_GPIO@GPC_MFPL', 'SPI1_MOSI:SYS_GPC_MFPL_PC6MFP_SPI1_MOSI@GPC_MFPL', 'UART0_nRTS:SYS_GPC_MFPL_PC6MFP_UART0_nRTS@GPC_MFPL', 'I2C1_SMBSUS:SYS_GPC_MFPL_PC6MFP_I2C1_SMBSUS@GPC_MFPL', 'BPWM3_CH3:SYS_GPC_MFPL_PC6MFP_BPWM3_CH3@GPC_MFPL', 'BPWM1_CH1:SYS_GPC_MFPL_PC6MFP_BPWM1_CH1@GPC_MFPL', 'TM1:SYS_GPC_MFPL_PC6MFP_TM1@GPC_MFPL', 'INT2:SYS_GPC_MFPL_PC6MFP_INT2@GPC_MFPL'] },
    { f: ['PC.7', 'GPIO:SYS_GPC_MFPL_PC7MFP_GPIO@GPC_MFPL', 'SPI1_MISO:SYS_GPC_MFPL_PC7MFP_SPI1_MISO@GPC_MFPL', 'UART0_nCTS:SYS_GPC_MFPL_PC7MFP_UART0_nCTS@GPC_MFPL', 'I2C1_SMBAL:SYS_GPC_MFPL_PC7MFP_I2C1_SMBAL@GPC_MFPL', 'BPWM3_CH2:SYS_GPC_MFPL_PC7MFP_BPWM3_CH2@GPC_MFPL', 'BPWM1_CH0:SYS_GPC_MFPL_PC7MFP_BPWM1_CH0@GPC_MFPL', 'TM0:SYS_GPC_MFPL_PC7MFP_TM0@GPC_MFPL', 'INT3:SYS_GPC_MFPL_PC7MFP_INT3@GPC_MFPL'] },
    { f: ['PC.14', 'GPIO:SYS_GPC_MFPH_PC14MFP_GPIO@GPC_MFPH', 'SPI1_MOSI:SYS_GPC_MFPH_PC14MFP_SPI1_MOSI@GPC_MFPH', 'SPI0_I2SMCLK:SYS_GPC_MFPH_PC14MFP_SPI0_I2SMCLK@GPC_MFPH', 'TM1:SYS_GPC_MFPH_PC14MFP_TM1@GPC_MFPH', 'DAC1_ST:SYS_GPC_MFPH_PC14MFP_DAC1_ST@GPC_MFPH'] },

    { f: ['PD.0', 'GPIO:SYS_GPD_MFPL_PD0MFP_GPIO@GPD_MFPL', 'SPI0_MOSI:SYS_GPD_MFPL_PD0MFP_SPI0_MOSI@GPD_MFPL', 'TM2:SYS_GPD_MFPL_PD0MFP_TM2@GPD_MFPL'] },
    { f: ['PD.1', 'GPIO:SYS_GPD_MFPL_PD1MFP_GPIO@GPD_MFPL', 'SPI0_MISO:SYS_GPD_MFPL_PD1MFP_SPI0_MISO@GPD_MFPL'] },
    { f: ['PD.2', 'GPIO:SYS_GPD_MFPL_PD2MFP_GPIO@GPD_MFPL', 'SPI0_CLK:SYS_GPD_MFPL_PD2MFP_SPI0_CLK@GPD_MFPL', 'UART0_RXD:SYS_GPD_MFPL_PD2MFP_UART0_RXD@GPD_MFPL'] },
    { f: ['PD.3', 'GPIO:SYS_GPD_MFPL_PD3MFP_GPIO@GPD_MFPL', 'SPI0_SS:SYS_GPD_MFPL_PD3MFP_SPI0_SS@GPD_MFPL', 'UART0_TXD:SYS_GPD_MFPL_PD3MFP_UART0_TXD@GPD_MFPL'] },
    { f: ['PD.15', 'GPIO:SYS_GPD_MFPH_PD15MFP_GPIO@GPD_MFPH', 'BPWM2_CH5:SYS_GPD_MFPH_PD15MFP_BPWM2_CH5@GPD_MFPH', 'TM3:SYS_GPD_MFPH_PD15MFP_TM3@GPD_MFPH', 'INT1:SYS_GPD_MFPH_PD15MFP_INT1@GPD_MFPH'] },

    { f: ['PF.0', 'GPIO:SYS_GPF_MFPL_PF0MFP_GPIO@GPF_MFPL', 'UART1_TXD:SYS_GPF_MFPL_PF0MFP_UART1_TXD@GPF_MFPL', 'I2C1_SCL:SYS_GPF_MFPL_PF0MFP_I2C1_SCL@GPF_MFPL', 'UART0_TXD:SYS_GPF_MFPL_PF0MFP_UART0_TXD@GPF_MFPL', 'I2C2_SCL:SYS_GPF_MFPL_PF0MFP_I2C2_SCL@GPF_MFPL', 'UART2_TXD:SYS_GPF_MFPL_PF0MFP_UART2_TXD@GPF_MFPL', 'I2C1_SMBAL:SYS_GPF_MFPL_PF0MFP_I2C1_SMBAL@GPF_MFPL', 'BPWM1_CH0:SYS_GPF_MFPL_PF0MFP_BPWM1_CH0@GPF_MFPL', 'ACMP0_O:SYS_GPF_MFPL_PF0MFP_ACMP0_O@GPF_MFPL', 'ICE_DAT:SYS_GPF_MFPL_PF0MFP_ICE_DAT@GPF_MFPL'] },
    { f: ['PF.1', 'GPIO:SYS_GPF_MFPL_PF1MFP_GPIO@GPF_MFPL', 'UART1_RXD:SYS_GPF_MFPL_PF1MFP_UART1_RXD@GPF_MFPL', 'I2C1_SDA:SYS_GPF_MFPL_PF1MFP_I2C1_SDA@GPF_MFPL', 'UART0_RXD:SYS_GPF_MFPL_PF1MFP_UART0_RXD@GPF_MFPL', 'I2C2_SDA:SYS_GPF_MFPL_PF1MFP_I2C2_SDA@GPF_MFPL', 'UART2_RXD:SYS_GPF_MFPL_PF1MFP_UART2_RXD@GPF_MFPL', 'I2C1_SMBSUS:SYS_GPF_MFPL_PF1MFP_I2C1_SMBSUS@GPF_MFPL', 'BPWM1_CH1:SYS_GPF_MFPL_PF1MFP_BPWM1_CH1@GPF_MFPL', 'ACMP1_O:SYS_GPF_MFPL_PF1MFP_ACMP1_O@GPF_MFPL', 'ICE_CLK:SYS_GPF_MFPL_PF1MFP_ICE_CLK@GPF_MFPL'] },
    { f: ['PF.2', 'GPIO:SYS_GPF_MFPL_PF2MFP_GPIO@GPF_MFPL', 'UART0_RXD:SYS_GPF_MFPL_PF2MFP_UART0_RXD@GPF_MFPL', 'I2C0_SDA:SYS_GPF_MFPL_PF2MFP_I2C0_SDA@GPF_MFPL', 'UART1_RXD:SYS_GPF_MFPL_PF2MFP_UART1_RXD@GPF_MFPL', 'XT1_OUT:SYS_GPF_MFPL_PF2MFP_XT1_OUT@GPF_MFPL', 'BPWM1_CH1:SYS_GPF_MFPL_PF2MFP_BPWM1_CH1@GPF_MFPL', 'ACMP3_O:SYS_GPF_MFPL_PF2MFP_ACMP3_O@GPF_MFPL', 'INT4:SYS_GPF_MFPL_PF2MFP_INT4@GPF_MFPL'] },
    { f: ['PF.3', 'GPIO:SYS_GPF_MFPL_PF3MFP_GPIO@GPF_MFPL', 'UART0_TXD:SYS_GPF_MFPL_PF3MFP_UART0_TXD@GPF_MFPL', 'I2C0_SCL:SYS_GPF_MFPL_PF3MFP_I2C0_SCL@GPF_MFPL', 'UART2_RXD:SYS_GPF_MFPL_PF3MFP_UART2_RXD@GPF_MFPL', 'BPWM0_CH3:SYS_GPF_MFPL_PF3MFP_BPWM0_CH3@GPF_MFPL', 'XT1_IN:SYS_GPF_MFPL_PF3MFP_XT1_IN@GPF_MFPL', 'BPWM1_CH0:SYS_GPF_MFPL_PF3MFP_BPWM1_CH0@GPF_MFPL', 'ACMP2_O:SYS_GPF_MFPL_PF3MFP_ACMP2_O@GPF_MFPL'] },
    { f: ['PF.4', 'GPIO:SYS_GPF_MFPL_PF4MFP_GPIO@GPF_MFPL', 'UART2_TXD:SYS_GPF_MFPL_PF4MFP_UART2_TXD@GPF_MFPL', 'UART2_nRTS:SYS_GPF_MFPL_PF4MFP_UART2_nRTS@GPF_MFPL', 'SPI0_MISO:SYS_GPF_MFPL_PF4MFP_SPI0_MISO@GPF_MFPL', 'BPWM2_CH1:SYS_GPF_MFPL_PF4MFP_BPWM2_CH1@GPF_MFPL', 'BPWM0_CH5:SYS_GPF_MFPL_PF4MFP_BPWM0_CH5@GPF_MFPL', 'I2C0_SDA:SYS_GPF_MFPL_PF4MFP_I2C0_SDA@GPF_MFPL', 'X32_OUT:SYS_GPF_MFPL_PF4MFP_X32_OUT@GPF_MFPL', 'BPWM2_CH5:SYS_GPF_MFPL_PF4MFP_BPWM2_CH5@GPF_MFPL', 'BPWM3_CH5:SYS_GPF_MFPL_PF4MFP_BPWM3_CH5@GPF_MFPL', 'ACMP3_WLAT:SYS_GPF_MFPL_PF4MFP_ACMP3_WLAT@GPF_MFPL'] },
    { f: ['PF.5', 'GPIO:SYS_GPF_MFPL_PF5MFP_GPIO@GPF_MFPL', 'UART2_RXD:SYS_GPF_MFPL_PF5MFP_UART2_RXD@GPF_MFPL', 'SPI1_SS:SYS_GPF_MFPL_PF5MFP_SPI1_SS@GPF_MFPL', 'UART2_nCTS:SYS_GPF_MFPL_PF5MFP_UART2_nCTS@GPF_MFPL', 'SPI0_CLK:SYS_GPF_MFPL_PF5MFP_SPI0_CLK@GPF_MFPL', 'BPWM2_CH0:SYS_GPF_MFPL_PF5MFP_BPWM2_CH0@GPF_MFPL', 'BPWM0_CH4:SYS_GPF_MFPL_PF5MFP_BPWM0_CH4@GPF_MFPL', 'I2C0_SCL:SYS_GPF_MFPL_PF5MFP_I2C0_SCL@GPF_MFPL', 'X32_IN:SYS_GPF_MFPL_PF5MFP_X32_IN@GPF_MFPL', 'ADC0_ST:SYS_GPF_MFPL_PF5MFP_ADC0_ST@GPF_MFPL', 'ACMP2_WLAT:SYS_GPF_MFPL_PF5MFP_ACMP2_WLAT@GPF_MFPL'] },
    { f: ['PF.6', 'GPIO:SYS_GPF_MFPL_PF6MFP_GPIO@GPF_MFPL', 'SPI0_MOSI:SYS_GPF_MFPL_PF6MFP_SPI0_MOSI@GPF_MFPL', 'I2C0_SDA:SYS_GPF_MFPL_PF6MFP_I2C0_SDA@GPF_MFPL', 'LLSI3_OUT:SYS_GPF_MFPL_PF6MFP_LLSI3_OUT@GPF_MFPL', 'BPWM2_CH4:SYS_GPF_MFPL_PF6MFP_BPWM2_CH4@GPF_MFPL', 'CLKO:SYS_GPF_MFPL_PF6MFP_CLKO@GPF_MFPL', 'TM3:SYS_GPF_MFPL_PF6MFP_TM3@GPF_MFPL', 'INT5:SYS_GPF_MFPL_PF6MFP_INT5@GPF_MFPL'] },
    { f: ['PF.14', 'GPIO:SYS_GPF_MFPH_PF14MFP_GPIO@GPF_MFPH', 'SPI0_SS:SYS_GPF_MFPH_PF14MFP_SPI0_SS@GPF_MFPH', 'LLSI3_OUT:SYS_GPF_MFPH_PF14MFP_LLSI3_OUT@GPF_MFPH', 'BPWM2_CH4:SYS_GPF_MFPH_PF14MFP_BPWM2_CH4@GPF_MFPH', 'CLKO:SYS_GPF_MFPH_PF14MFP_CLKO@GPF_MFPH', 'TM3:SYS_GPF_MFPH_PF14MFP_TM3@GPF_MFPH', 'INT5:SYS_GPF_MFPH_PF14MFP_INT5@GPF_MFPH'] },
    { f: ['PF.15', 'GPIO:SYS_GPF_MFPH_PF15MFP_GPIO@GPF_MFPH', 'UART0_nRTS:SYS_GPF_MFPH_PF15MFP_UART0_nRTS@GPF_MFPH', 'BPWM1_CH0:SYS_GPF_MFPH_PF15MFP_BPWM1_CH0@GPF_MFPH', 'TM2:SYS_GPF_MFPH_PF15MFP_TM2@GPF_MFPH', 'CLKO:SYS_GPF_MFPH_PF15MFP_CLKO@GPF_MFPH', 'INT4:SYS_GPF_MFPH_PF15MFP_INT4@GPF_MFPH'] }
];


NUTOOL_PIN.g_cfg_gpiosDescriptions = [
    'ACMP0_N:Analog comparator 0 negative input  pin.',
    'ACMP0_O:Analog comparator 0 output pin.',
    'ACMP0_P0:Analog comparator 0 positive input 0 pin.',
    'ACMP0_P1:Analog comparator 0 positive input 1 pin.',
    'ACMP0_P2:Analog comparator 0 positive input 2 pin.',
    'ACMP0_P3:Analog comparator 0 positive input 3 pin.',
    'ACMP0_WLAT:Analog comparator 0 window latch input pin',
    'ACMP1_N:Analog comparator 1 negative input  pin.',
    'ACMP1_O:Analog comparator 1 output pin.',
    'ACMP1_P0:Analog comparator 1 positive input 0 pin.',
    'ACMP1_P1:Analog comparator 1 positive input 1 pin.',
    'ACMP1_P2:Analog comparator 1 positive input 2 pin.',
    'ACMP1_P3:Analog comparator 1 positive input 3 pin.',
    'ACMP1_WLAT:Analog comparator 1 window latch input pin',
    'ACMP2_N:Analog comparator 2 negative input  pin.',
    'ACMP2_O:Analog comparator 2 output pin.',
    'ACMP2_P0:Analog comparator 2 positive input 0 pin.',
    'ACMP2_P1:Analog comparator 2 positive input 1 pin.',
    'ACMP2_P2:Analog comparator 2 positive input 2 pin.',
    'ACMP2_P3:Analog comparator 2 positive input 3 pin.',
    'ACMP2_WLAT:Analog comparator 2 window latch input pin',
    'ACMP3_N:Analog comparator 3 negative input  pin.',
    'ACMP3_O:Analog comparator 3 output pin.',
    'ACMP3_P0:Analog comparator 3 positive input 0 pin.',
    'ACMP3_P1:Analog comparator 3 positive input 1 pin.',
    'ACMP3_P2:Analog comparator 3 positive input 2 pin.',
    'ACMP3_P3:Analog comparator 3 positive input 3 pin.',
    'ACMP3_WLAT:Analog comparator 3 window latch input pin',
    'ADC0_CH0:ADC0 channel 0 analog input.',
    'ADC0_CH1:ADC0 channel 1 analog input.',
    'ADC0_CH2:ADC0 channel 2 analog input.',
    'ADC0_CH3:ADC0 channel 3 analog input.',
    'ADC0_CH4:ADC0 channel 4 analog input.',
    'ADC0_CH5:ADC0 channel 5 analog input.',
    'ADC0_CH6:ADC0 channel 6 analog input.',
    'ADC0_CH7:ADC0 channel 7 analog input.',
    'ADC0_CH8:ADC0 channel 8 analog input.',
    'ADC0_CH9:ADC0 channel 9 analog input.',
    'ADC0_CH10:ADC0 channel 10 analog input.',
    'ADC0_CH11:ADC0 channel 11 analog input.',
    'ADC0_CH12:ADC0 channel 12 analog input.',
    'ADC0_CH13:ADC0 channel 13 analog input.',
    'ADC0_CH14:ADC0 channel 14 analog input.',
    'ADC0_CH15:ADC0 channel 15 analog input.',
    'ADC0_ST:ADC0 external trigger input pin.',
    'BPWM0_CH0:BPWM0 channel 0 output/capture input.',
    'BPWM0_CH1:BPWM0 channel 1 output/capture input.',
    'BPWM0_CH2:BPWM0 channel 2 output/capture input.',
    'BPWM0_CH3:BPWM0 channel 3 output/capture input.',
    'BPWM0_CH4:BPWM0 channel 4 output/capture input.',
    'BPWM0_CH5:BPWM0 channel 5 output/capture input.',
    'BPWM1_CH0:BPWM1 channel 0 output/capture input.',
    'BPWM1_CH1:BPWM1 channel 1 output/capture input.',
    'BPWM1_CH2:BPWM1 channel 2 output/capture input.',
    'BPWM1_CH3:BPWM1 channel 3 output/capture input.',
    'BPWM1_CH4:BPWM1 channel 4 output/capture input.',
    'BPWM1_CH5:BPWM1 channel 5 output/capture input.',
    'BPWM2_CH0:BPWM2 channel 0 output/capture input.',
    'BPWM2_CH1:BPWM2 channel 1 output/capture input.',
    'BPWM2_CH2:BPWM2 channel 2 output/capture input.',
    'BPWM2_CH3:BPWM2 channel 3 output/capture input.',
    'BPWM2_CH4:BPWM2 channel 4 output/capture input.',
    'BPWM2_CH5:BPWM2 channel 5 output/capture input.',
    'BPWM3_CH0:BPWM3 channel 0 output/capture input.',
    'BPWM3_CH1:BPWM3 channel 1 output/capture input.',
    'BPWM3_CH2:BPWM3 channel 2 output/capture input.',
    'BPWM3_CH3:BPWM3 channel 3 output/capture input.',
    'BPWM3_CH4:BPWM3 channel 4 output/capture input.',
    'BPWM3_CH5:BPWM3 channel 5 output/capture input.',
    'CLKO:Clock Out',
    'DAC0_OUT:DAC0 channel  analog output.',
    'DAC0_ST:DAC0 external trigger input.',
    'DAC1_OUT:DAC1 channel  analog output.',
    'DAC1_ST:DAC1 external trigger input.',
    'DAC2_OUT:DAC2 channel  analog output.',
    'DAC2_ST:DAC2 external trigger input.',
    'DAC3_OUT:DAC3 channel  analog output.',
    'DAC3_ST:DAC3 external trigger input.',
    'I2C0_SCL:I2C0 clock pin.',
    'I2C0_SDA:I2C0 data input/output pin.',
    'I2C0_SMBAL:I2C0 SMBus SMBALTER pin ',
    'I2C0_SMBSUS:I2C0 SMBus SMBSUS pin (PMBus CONTROL pin)',
    'I2C1_SCL:I2C1 clock pin.',
    'I2C1_SDA:I2C1 data input/output pin.',
    'I2C1_SMBAL:I2C1 SMBus SMBALTER pin ',
    'I2C1_SMBSUS:I2C1 SMBus SMBSUS pin (PMBus CONTROL pin)',
    'I2C2_SCL:I2C2 clock pin.',
    'I2C2_SDA:I2C2 data input/output pin.',
    'I2C2_SMBAL:I2C2 SMBus SMBALTER pin ',
    'I2C2_SMBSUS:I2C2 SMBus SMBSUS pin (PMBus CONTROL pin)',
    'I3C0_SCL:',
    'I3C0_SDA:',
    'I3C1_SCL:',
    'I3C1_SDA:',
    'ICE_CLK:Serial wired debugger clock pin.',
    'ICE_DAT:Serial wired debugger data pin.',
    'INT0:External interrupt 0 input pin.',
    'INT1:External interrupt 1 input pin.',
    'INT2:External interrupt 2 input pin.',
    'INT3:External interrupt 3 input pin.',
    'INT4:External interrupt 4 input pin.',
    'INT5:External interrupt 5 input pin.',
    'LLSI0_OUT:LED Lighting Strip Interface 0 output pin.',
    'LLSI1_OUT:LED Lighting Strip Interface 1 output pin.',
    'LLSI2_OUT:LED Lighting Strip Interface 2 output pin.',
    'LLSI3_OUT:LED Lighting Strip Interface 3 output pin.',
    'LLSI4_OUT:LED Lighting Strip Interface 4 output pin.',
    'LLSI5_OUT:LED Lighting Strip Interface 5 output pin.',
    'SPDH_HSA:',
    'SPI_CLK_MUX:',
    'SPI_MISO_MUX:SPI_ MISOM (Master In, Slave Out) pin.',
    'SPI_MOSI_MUX:SPI_ MOSIM (Master Out, Slave In) pin.',
    'SPI_SS_MUX:SPI_ slave select M pin.',
    'SPI0_CLK:SPI0 serial clock pin.',
    'SPI0_I2SMCLK:SPI0 I2S master clock output pin',
    'SPI0_MISO:SPI0 MISO (Master In, Slave Out) pin.',
    'SPI0_MOSI:SPI0 MOSI (Master Out, Slave In) pin.',
    'SPI0_SS:SPI0 slave select  pin.',
    'SPI1_CLK:SPI1 serial clock pin.',
    'SPI1_I2SMCLK:SPI1 I2S master clock output pin',
    'SPI1_MISO:SPI1 MISO (Master In, Slave Out) pin.',
    'SPI1_MOSI:SPI1 MOSI (Master Out, Slave In) pin.',
    'SPI1_SS:SPI1 slave select  pin.',
    'SPI2_CLK:SPI2 serial clock pin.',
    'SPI2_I2SMCLK:SPI2 I2S master clock output pin',
    'SPI2_MISO:SPI2 MISO (Master In, Slave Out) pin.',
    'SPI2_MOSI:SPI2 MOSI (Master Out, Slave In) pin.',
    'SPI2_SS:SPI2 slave select  pin.',
    'TM0:Timer0 event counter input/toggle output pin.',
    'TM0_EXT:Timer0 external capture input/toggle output pin.',
    'TM1:Timer1 event counter input/toggle output pin.',
    'TM1_EXT:Timer1 external capture input/toggle output pin.',
    'TM2:Timer2 event counter input/toggle output pin.',
    'TM2_EXT:Timer2 external capture input/toggle output pin.',
    'TM3:Timer3 event counter input/toggle output pin.',
    'TM3_EXT:Timer3 external capture input/toggle output pin.',
    'UART0_nCTS:UART0 clear to Send input pin.',
    'UART0_nRTS:UART0 request to Send output pin.',
    'UART0_RXD:UART0 data receiver input pin.',
    'UART0_TXD:UART0 data transmitter output pin.',
    'UART1_nCTS:UART1 clear to Send input pin.',
    'UART1_nRTS:UART1 request to Send output pin.',
    'UART1_RXD:UART1 data receiver input pin.',
    'UART1_TXD:UART1 data transmitter output pin.',
    'UART2_nCTS:UART2 clear to Send input pin.',
    'UART2_nRTS:UART2 request to Send output pin.',
    'UART2_RXD:UART2 data receiver input pin.',
    'UART2_TXD:UART2 data transmitter output pin.',
    'VDET_P0:Voltage detector positive input 0 pin.',
    'VDET_P1:Voltage detector positive input 1 pin.',
    'X32_IN:External 32.768 kHz crystal input pin.',
    'X32_OUT:External 32.768 kHz crystal output pin.',
    'XT1_IN:External 4~24 MHz (high speed) crystal input pin.',
    'XT1_OUT:External 4~24 MHz (high speed) crystal output pin.'
];

NUTOOL_PIN.g_cfg_regDescriptions = {};
NUTOOL_PIN.g_cfg_regDescriptions.GPA_MFPL = '0x50000030';
NUTOOL_PIN.g_cfg_regDescriptions.GPA_MFPH = '0x50000034';
NUTOOL_PIN.g_cfg_regDescriptions.GPB_MFPL = '0x50000038';
NUTOOL_PIN.g_cfg_regDescriptions.GPB_MFPH = '0x5000003C';
NUTOOL_PIN.g_cfg_regDescriptions.GPC_MFPL = '0x50000040';
NUTOOL_PIN.g_cfg_regDescriptions.GPC_MFPH = '0x50000044';
NUTOOL_PIN.g_cfg_regDescriptions.GPD_MFPL = '0x50000048';
NUTOOL_PIN.g_cfg_regDescriptions.GPD_MFPH = '0x5000004C';
NUTOOL_PIN.g_cfg_regDescriptions.GPE_MFPL = '0x50000050';
NUTOOL_PIN.g_cfg_regDescriptions.GPE_MFPH = '0x50000054';
NUTOOL_PIN.g_cfg_regDescriptions.GPF_MFPL = '0x50000058';
NUTOOL_PIN.g_cfg_regDescriptions.GPF_MFPH = '0x5000005C';

NUTOOL_PIN.g_cfg_gpioMatrix = [];
NUTOOL_PIN.g_cfg_shareBits = [];
NUTOOL_PIN.g_cfg_addGPIO = {};
NUTOOL_PIN.g_cfg_unusedGPIO = {
    'NUC1263ZD4AE(QFN33)': {
        'ALL': ['I3C0', 'I3C1', 'USB']
    },
    'NUC1263ND4AE(QFN48)': {
        'ALL': ['I3C0', 'I3C1', 'USB']
    },
    'NUC1263LD4AE(LQFP48)': {
        'ALL': ['SPD5']
    },
    'NUC1263SD4AE(LQFP64)': {
        'ALL': ['SPD5']
    }
};

NUTOOL_PIN.decidepackageNumber = function (given_partNumber_package) {
    var partNumber_package,
        partNumber;

    if (typeof given_partNumber_package === 'undefined') {
        partNumber_package = NUTOOL_PIN.getg_partNumber_package();
    }
    else {
        partNumber_package = given_partNumber_package;
    }

    NUTOOL_PIN.g_packageNumber = partNumber_package.substring(partNumber_package.indexOf('(') + 1);
    NUTOOL_PIN.g_packageNumber = NUTOOL_PIN.g_packageNumber.substring(0, NUTOOL_PIN.g_packageNumber.indexOf(')'));

    partNumber = partNumber_package.substring(0, partNumber_package.indexOf('('));
    switch (NUTOOL_PIN.g_packageNumber) {
        case 'QFN33':
            switch (partNumber) {
                default:
                    NUTOOL_PIN.g_packageNumberIndex = "QFN33_SPD5(5*5)";
                    break;
            }
            break;
        case 'QFN48':
            switch (partNumber) {
                default:
                    NUTOOL_PIN.g_packageNumberIndex = "QFN48_SPD5(7*7)";
                    break;
            }
            break;
        case 'LQFP48':
            switch (partNumber) {
                default:
                    NUTOOL_PIN.g_packageNumberIndex = "ULQFP48(7*7)";
                    break;
            }
            break;
        case 'LQFP64':
            switch (partNumber) {
                default:
                    NUTOOL_PIN.g_packageNumberIndex = "ULQFP64(7*7)";
                    break;
            }
            break;
            partNumber_package = null;
            partNumber = null;
    };
}
