
#if (NUCODEGEN_PDMA_CH0 || NUCODEGEN_PDMA_CH1 || NUCODEGEN_PDMA_CH2 || NUCODEGEN_PDMA_CH3 || NUCODEGEN_PDMA_CH4)
#if (NUCODEGEN_PDMA_CH0_INT || NUCODEGEN_PDMA_CH1_INT || NUCODEGEN_PDMA_CH2_INT || NUCODEGEN_PDMA_CH3_INT || NUCODEGEN_PDMA_CH4_INT)
void PDMA_IRQHandler(void)
{
    uint32_t u32Status = PDMA_GET_INT_STATUS(PDMA);

    if (u32Status & PDMA_INTSTS_TDIF_Msk)     /* done */
    {
        /* Transfer done */
    }
    else
        printf("Unexpected interrupt !!\n");
}
#endif  //NUCODEGEN_PDMA_CH0_INT || NUCODEGEN_PDMA_CH1_INT || NUCODEGEN_PDMA_CH2_INT || NUCODEGEN_PDMA_CH3_INT || NUCODEGEN_PDMA_CH4_INT
#endif  //NUCODEGEN_PDMA_CH0 || NUCODEGEN_PDMA_CH1 || NUCODEGEN_PDMA_CH2 || NUCODEGEN_PDMA_CH3 || NUCODEGEN_PDMA_CH4
